### ISSUE TITLE
Run Completion Delay

### ISSUE THREAD

**Issue by diegocatao** [cypress-io/github-action#1007]
I have two groups of tests, the 2nd one should start only after the first one.  I have set an amount of time on "Run Completion Delay" (Cypress Cloud) so that Cypress would wait for the 2nd group to be ready and start its execution, but after the 2nd group execution, I don't need that competition delay again, b/c there is nothing else to be executed.

How could I skip that "Run Completion Delay" when the 2nd group execution finishes?

**Comment by nagash77** [comment]
Hi @diegocatao Issues in the repo are reserved for bugs and feature requests only.  Please check out the Cypress Discord Community [![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord), for help debugging or answering questions on how to use Cypress.
