### ISSUE TITLE
Figure out how to run Firefox better

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/github-action#104]
- right now the only way to run Firefox is to use `--user 1001` to match the permissions GH sets when creating a home folder for the user

```
container:
  image: cypress/browsers:node12.16.1-chrome80-ff73
  options: --user 1001
```

```
docker.io/cypress/browsers:node12.16.1-chrome80-ff73
/usr/bin/docker create --name 9841aeea80f6424291fc77ef4b420dd6_cypressbrowsersnode12161chrome80ff73_ee5fd3 
--label e87b52 
--workdir /__w/github-action/github-action 
--network github_network_7218f6f710d149c59f24a8cab63bbe10  
-e "HOME=/github/home"
```

Permissions on the home folder

```
Run ls -la /github/home
total 8
drwxr-xr-x 2 1001  115 4096 Mar  5 15:33 .
drwxr-xr-x 4 root root 4096 Mar  5 15:33 ..
```

It would be nice to run with any non-root user, for example our cypress-docker-images have `node` user with id 1000.

PS: the `1001` user works but has group id of 0

```
$ id
uid=1001 gid=0(root) groups=0(root)
```

## Preferred

```
container:
  image: cypress/browsers:node12.16.1-chrome80-ff73
  options: --user node
```

**Comment by kamranayub** [comment]
Yeah, attempting to make a sample PWA that has FF under CI but I may throw in the towel for now, it seems to start but then will just hang endlessly. It could be related to previous hanging issues with Shadow DOM (this is an Ionic app). The tests will pass locally in FF, though. Since it's beta, it's not a huge deal to explain away.

**Comment by jennifer-shehane** [comment]
@kamranayub Make sure to update to latest Cypress because we have been fixing the shadow dom hanging as we find them. Today, we're only aware of hanging when using `.scrollTo` on shadow dom with the experimental feature, so if you do find something isolated to Firefox, open an issue.

**Comment by kamranayub** [comment]
I'm still investigating but it hangs on my window `Notification` test suite, though it will work in an isolated way in some of my tests. I am testing a cross-origin domain so that might have something to do with it but like I said, it passes locally in FF 78 🤔 I may be able to grab video from it.

**Comment by kamranayub** [comment]
So what I am seeing is a little interesting. It appears that my tests are passing but then mid-way through a test suite, GitHub Actions does not get any more logging/output and there was a 12 minute gap until finally my job hit the wait limit. The video file for the test suite that "failed" (all the tests were passing in the logs at the point of failure) is 3MB and corrupt, I can't open it, but other video files I can.

![image](https://user-images.githubusercontent.com/563819/88873585-96bcef80-d1e2-11ea-9499-3b3a0322b33b.png)

The output then just cuts off and times out:

![image](https://user-images.githubusercontent.com/563819/88873637-bbb16280-d1e2-11ea-9413-c9d2d45481ce.png)

Notice at the very end, a gap of 12 minutes. This is why I think it hangs for some reason and it seems to be random.

**Comment by emilgoldsmith** [comment]
I was running into issues with a custom docker container for the job using `--user 1001` because of permissions of the files created in the build stage of the container (in the dockerfile).

I found a solution that I could imagine may very well break some other stuff haha, but it doesn't look like it's breaking any of my things I need to do anyway! For my usecase it seems a lot less intrusive and in case it is for others as well I just wanted to share.

And that was simply to have
```yml
jobs:
  job-name:
    env:
      HOME: ""
```

And it's important not just to do it for the cypress step because then in the install steps it seems like Cypress installs something in the home folders that it needs and it breaks Cypress, if you have it through the whole job like this though, it works perfectly :). 

When HOME is set to empty string Firefox allows you to run it as root nicely, and I can keep all the permissions to access my files in the container easily

**Comment by KleisKlasKluss** [comment]
> I was running into issues with a custom docker container for the job using `--user 1001` because of permissions of the files created in the build stage of the container (in the dockerfile).
> 
> I found a solution that I could imagine may very well break some other stuff haha, but it doesn't look like it's breaking any of my things I need to do anyway! For my usecase it seems a lot less intrusive and in case it is for others as well I just wanted to share.
> 
> And that was simply to have
> 
> ```yaml
> jobs:
>   job-name:
>     env:
>       HOME: ""
> ```
> 
> And it's important not just to do it for the cypress step because then in the install steps it seems like Cypress installs something in the home folders that it needs and it breaks Cypress, if you have it through the whole job like this though, it works perfectly :).
> 
> When HOME is set to empty string Firefox allows you to run it as root nicely, and I can keep all the permissions to access my files in the container easily

Thanks @emilgoldsmith! 🎉  This solved a similar issue that I've been struggling with for quite some time.

**Comment by MikeMcC399** [comment]
The original post for this issue says:

> right now the only way to run Firefox is to use --user 1001 to match the permissions GH sets when creating a home folder for the user

however this refers only to running Firefox in a Docker container provided by [cypress-io/cypress-docker-images](https://github.com/cypress-io/cypress-docker-images).

When using a [GitHub runner](https://github.com/actions/runner-images) directly without a Docker container from [cypress-io/cypress-docker-images](https://github.com/cypress-io/cypress-docker-images) there is no need to supply a user. Firefox was added to the GitHub runners in March 2020.

The [.github/workflows/example-firefox.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-firefox.yml) demonstrates testing with Firefox without specifying `--user 1001`.

- This is related to https://github.com/cypress-io/github-action/issues/735.

**Comment by Fanch-** [comment]
Got into this issue.
Works fine with **--user 1001** on ubuntu github runners.

But for a custom self-hosted runner got into this other issue : https://github.com/actions/checkout/issues/956#issue-1404930646

bahmutov Preferred way solved it : 
` options: --user node`

**Comment by MikeMcC399** [comment]
@Fanch- 

Were you using a Docker container from https://github.com/cypress-io/cypress-docker-images when you applied

`options: --user node`

or did you have Firefox directly installed in your self-hosted runner? What operating system was your self-hosted runner? Ubuntu or something else?

**Comment by Fanch-** [comment]
Yes using the docker image **cypress/browsers:node16.16.0-chrome107-ff107** in a container action.
Runner "Light Ubuntu" with few packages.

Complexity for us is : 

- runners are managed by a dedicated team and are very light.
- they don't want to manage custom runners with packages pre-installed for everybody (in our case https://docs.cypress.io/guides/getting-started/installing-cypress#Linux-Prerequisites).
- packages installation takes "forever" which is an issue to resolve but to not be blocked by the support, we bypass it for the time being; using the container action and not the js action directly.
- we could manage a custom image with our other dependencies ourself, as we used to in travis, but we'll try without it with GA (cache)

I hope this gives you some context.

**Comment by MikeMcC399** [comment]
Closing, as this topic belongs in the [cypress-io/cypress-docker-images/issues/](https://github.com/cypress-io/cypress-docker-images/issues/) list.

[README > Docker image](https://github.com/cypress-io/github-action#docker-image) recommends specifying

```yml
    container:
      image: cypress/browsers:latest
      options: --user 1001
```

and refers to [cypress-io/cypress-docker-images](https://github.com/cypress-io/cypress-docker-images) for further information.
