### ISSUE TITLE
cypress-io/github-action@v6 is always running on node 20 even when using setup-node with node-version 18

### ISSUE THREAD

**Issue by CaiqueCoelho** [cypress-io/github-action#1086]
I'm trying to run a project with cypress-io/github-action@v6 and I need to run the project with node-version 18, I'm using setu-node with 18 to try to override the cypress-io/github-action version, but we still are getting node Node.js v20.8.1

<img width="560" alt="Captura de Tela 2023-11-30 às 12 22 26" src="https://github.com/cypress-io/github-action/assets/29831309/1eee4715-4ff2-41ab-8f43-499209ba7eb1">
<img width="1002" alt="Captura de Tela 2023-11-30 às 12 22 43" src="https://github.com/cypress-io/github-action/assets/29831309/23557076-d787-4205-ba82-51fe4af16826">

**Comment by MikeMcC399** [comment]
Closing, since the action works as documented.
