### ISSUE TITLE
Xvfb missing 

### ISSUE THREAD

**Issue by dapo-maraboo** [cypress-io/github-action#1114]
I keep getting this error locally using `cypress-io/github-action@v6` what am I missing? I thought it should already come with all the required dependencies

<img width="806" alt="Screenshot 2024-01-22 at 13 20 32" src="https://github.com/cypress-io/github-action/assets/128864202/616fe0e0-856c-46ae-b38f-ff8bf060da90">

**Comment by MikeMcC399** [comment]
@dapo-maraboo 

> I keep getting this error locally using `cypress-io/github-action@v6` what am I missing? I thought it should already come with all the required dependencies

Are you using a GitHub-hosted runner or a self-hosted runner? Am I right that when you say "locally using `cypress-io/github-action@v6`" you mean that you are using a self-hosted runner?

[GitHub-hosted ubuntu-22.04](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md) has `xvfb` `2:21.1.4-2ubuntu1.7~22.04.5` pre-installed (see [Installed apt packages](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#installed-apt-packages)).

If you are using a self-hosted runner, then you will need to make sure that the dependencies listed under https://on.cypress.io/required-dependencies for Ubuntu are already installed on your runner:

```shell
apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb
```

**Comment by dapo-maraboo** [comment]
Thanks @MikeMcC399 I look into your suggestions
When I said locally I meant using the act package to run the ci process locally on my machine (Macbook Intel chip).

**Comment by MikeMcC399** [comment]
@dapo-maraboo 

> I look into your suggestions

Good. If you still have an issue, please explain what command you are using to run CI.

> When I said locally I meant using the act package to run the ci process locally on my machine (Macbook Intel chip).

`cypress-io/github-action@v6` only runs on a GitHub runner so there may be a misunderstanding.

**Comment by dapo-maraboo** [comment]
Still having some issues, cypress cant seem to connect to the api server within the CI
I dont know what I'm missing

    `  services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: mbtestdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432        

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Tag Docker Images
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t tests --build-arg BUILDKIT_INLINE_CACHE=1 --target test .
        
      - name: Start the MarabooApi
        run: |
          docker run  -d \
            -e APP_ENV="test" \
            -e BASE_DIR="./" \
            -e DB_USER=postgres \
            -e DB_PASSWD=postgres \
            -e DB_DATABASE=mbtestdb \
            -e DB_HOST=localhost \
            -e GOOGLE_CLIENT_IDS="test_client_id_one","test_client_id_two" \
            -e DB_PORT=5432 \
            -v .:/swapapp/ \
            -p 8080:8080 \
            --network host \
            --rm tests:latest
          
    - name: Check api status
       run: |
         curl -v http://localhost:8080
      - name: Install Yarn
        run: npm install -g yarn

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          wait-on: http://localhost:8080
          project: ${{ github.workspace }}/cypress`

**Comment by MikeMcC399** [comment]
@dapo-maraboo 

Have you resolved the issue with `xvfb`?

**Comment by MikeMcC399** [comment]
@dapo-maraboo 

Since your original issue is resolved I am going to close this issue.

The issue list here is intended for users to report bugs in the action. It is not primarily intended as a "how-to" support tool.

You can open a new issue for your follow-on problem, however you should be prepared to supply your full workflow and log files.

The Cypress technical community on Discord may also be able to help you:

[![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord) (click on button)
