### ISSUE TITLE
Node.js 16 deprecations in triage workflows

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/github-action#1121]
Workflows set up by Cypress.io to support triaging are producing deprecation warnings:

- [add-issue-to-triage-board.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/add-issue-to-triage-board.yml)

> add-to-triage-project-board / add-contributor-pr-comment
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-node@v3, actions/github-script@v6. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

https://github.com/cypress-io/github-action/blob/9eda80f1cd0919c1edfa090b4f5b6ed5fce35878/.github/workflows/add-issue-to-triage-board.yml#L9-L14

-> [cypress-io/cypress/.github/workflows/triage_add_to_project.yml@develop](https://github.com/cypress-io/cypress/blob/develop/.github/workflows/triage_add_to_project.yml)

- [triage_closed_issue_comment.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/triage_closed_issue_comment.yml)

> closed-issue-comment / handle-comment-scenarios
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-node@v3, actions/github-script@v6. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

https://github.com/cypress-io/github-action/blob/9eda80f1cd0919c1edfa090b4f5b6ed5fce35878/.github/workflows/triage_closed_issue_comment.yml#L6-L11

-> [cypress-io/cypress/.github/workflows/triage_handle_new_comments.yml@develop](https://github.com/cypress-io/cypress/blob/develop/.github/workflows/triage_handle_new_comments.yml)

The source of the workflows is outside of the scope of this repo.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

If triaging in this form is no longer being used then the workflows with deprecations should be disabled.

If the workflows are still being used, then they need to be updated to run without deprecation warnings:

`actions/checkout@v3` => `@v4`
`actions/setup-node@v3` => `@v4`
`actions/github-script@v6` => `@v7`

- See also open issue https://github.com/cypress-io/cypress/issues/28653

**Comment by jennifer-shehane** [comment]
Yah these still are used, it's just no longer public because it's just our internal triage process of getting through new messages.

**Comment by MikeMcC399** [comment]
I added the links to the workflows causing the deprecations:

-> [cypress-io/cypress/.github/workflows/triage_add_to_project.yml@develop](https://github.com/cypress-io/cypress/blob/develop/.github/workflows/triage_add_to_project.yml)

-> [cypress-io/cypress/.github/workflows/triage_handle_new_comments.yml@develop](https://github.com/cypress-io/cypress/blob/develop/.github/workflows/triage_handle_new_comments.yml)

and correct that comment that these are not visible.

- PR #28879 is planned to fix this issue.

**Comment by MikeMcC399** [comment]
Testing comment workflow on closed issue.
