### ISSUE TITLE
Action stuck at Warning: vkCreateInstance: Found no drivers!

### ISSUE THREAD

**Issue by morremeyer** [cypress-io/github-action#1136]
We're having runs on PRs with this action get stuck with

```
Warning: vkCreateInstance: Found no drivers!
Warning: vkCreateInstance failed with VK_ERROR_INCOMPATIBLE_DRIVER
    at CheckVkSuccessImpl (../../third_party/dawn/src/dawn/native/vulkan/VulkanError.cpp:88)
    at CreateVkInstance (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:458)
    at Initialize (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:344)
    at Create (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:266)
    at operator() (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:521)
```

for hours.

It looks like once this error occurs, the action keeps running indefinitely until it will be terminated by GitHub.

See for example:

* https://github.com/envelope-zero/frontend/actions/runs/8122963743/job/22202908208?pr=1572
* https://github.com/envelope-zero/frontend/actions/runs/8117820097/job/22190843300?pr=1574

This started at 2024-02-28T18:50Z with https://github.com/envelope-zero/frontend/actions/runs/8085573515?pr=1550.

I did some research, but could not find anything for this error related to cypress so far.

**Comment by MikeMcC399** [comment]
@morremeyer 

This does not look like an error caused by the Cypress GitHub Action. There is an identical stack trace on https://askubuntu.com/questions/1477966/using-chromium-with-vulkan which may help you. You might want to try testing with different browsers such as the built-in Electron or Google Chrome instead of Chromium.

In the meantime, I suggest to add a [timeout](https://github.com/cypress-io/github-action/blob/master/README.md#timeouts)  to prevent the job hanging for a long time.

**Comment by morremeyer** [comment]
@MikeMcC399 Thanks for the pointers! I'll dig into this and document any findings here in case anyone runs into it in the future.

**Comment by morremeyer** [comment]
Since this posed the danger of leading me to the realm of "understanding display drivers", which I do not have desire to explore, I decided to see what happens if I switch the tests to Electron.

Doing so did not get rid of the error message, as can be seen in https://github.com/envelope-zero/frontend/actions/runs/8124771638/job/22206650558?pr=1576, where it occurs once

**However**, the run does not get stuck when this error pops up.

I'm going to count this as a win. 
Thanks @MikeMcC399 for the poke in the right direction!

**Comment by roadSurfer** [comment]
We are seeing this when using Cypress 13.6.6 and Electron 118 when running tests within the `/home/jason/Work/planning/qa/cypress-tests/.gitlab-ci.yml` image as part of a GitLab pipeline. The error apperas on ubuntu 22.04 and CentOS 7 Docker hosts.

Another error which may be related only appears on the CentOS hosts:
```
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
```

However any hangs are intermittent and I have not been able to pin down what the actual cause is. It might just be coincidence that the message appears around the time of a hang.

Is there any other logging/debugging we should enable?

**Comment by MikeMcC399** [comment]
@roadSurfer 

It looks like there are multiple users experiencing an issue with `vkCreateInstance`, however you say that you are seeing this in a GitLab pipeline.

This is the issue list for the Cypress GitHub JavaScript Action. So problems on GitLab don't belong here.

Can I ask you to please submit a new issue to the main Cypress issue list on https://github.com/cypress-io/cypress/issues ?

Regarding:

> libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)

In my experience this is an error which often shows on headless systems and it can be ignored.

**Comment by MikeMcC399** [comment]
@roadSurfer 

No problem about being in the wrong issue list! 🙂

**Comment by MikeMcC399** [comment]
@morremeyer 

Since other users are also reporting this issue and the root cause is still unclear, can I ask you if you are running Cypress in a Docker container or not?

**Comment by morremeyer** [comment]
@MikeMcC399 Sure! If the action doesn't use docker under the hood, then no. 

This is the configuration we currently use: https://github.com/envelope-zero/frontend/blob/3b4effc9aff0814ccd49b933dfad8c8a1348e26b/.github/workflows/workflow.yml#L67-L84

**Comment by MikeMcC399** [comment]
@morremeyer 

Many thanks for your confirmation! Hopefully it will soon become clear what is causing this issue!

No, GitHub Actions does not use Docker in any hidden way., only if it is explicitly configured, for instance like the following in a workflow:

```yml
    container:
      image: cypress/browsers:latest
      options: --user 1001

```

**Comment by sbrawner** [comment]
> @morremeyer
> 
> Many thanks for your confirmation! Hopefully it will soon become clear what is causing this issue!
> 
> No, GitHub Actions does not use Docker in any hidden way., only if it is explicitly configured, for instance like the following in a workflow:
> 
> ```yaml
>     container:
>       image: cypress/browsers:latest
>       options: --user 1001
> ```

I am using it in docker/kube and am having this exact issue.  Backing down a version to see if it still occurs.

**Comment by MikeMcC399** [comment]
@sbrawner 

Thanks for contributing your experience too! To test if this might be related to the Electron upgrade in [cypress@13.6.5](https://docs.cypress.io/guides/references/changelog#13-6-5) from `25.8.4` to `27.1.3` you might like to try reverting to [cypress@13.6.4](https://docs.cypress.io/guides/references/changelog#13-6-4).

**Comment by MikeMcC399** [comment]
@marcdix 

> I downgraded to 13.6.4 as you suggested and the error is gone.

Many thanks for your feedback! I passed that on to other users to try out as well.

**Comment by roshnimridha04** [comment]
@MikeMcC399 Is there a plan to resolve this issue in future release of cypress as downgrading version to 13.6.4 works?

**Comment by MikeMcC399** [comment]
@roshnimridha04 
> Is there a plan to resolve this issue in future release of cypress as downgrading version to 13.6.4 works?

- There is an open issue https://github.com/cypress-io/cypress/issues/29085 in the Cypress repo for this which you can follow. It's not tracked in the `github-action` repo, since it is not a `github-action` bug. I suspect it may need Cypress to update the version of Electron it uses, but there is no confirmation of that theory at this time.

**Comment by BarbaraGodayol** [comment]
Hello, I'm facing the same error. I have different github actions running but they found the mentioned error and all the pipelines can't continue.
Versions about my execution: 

![Image](https://github.com/user-attachments/assets/23d3bdca-a18c-481b-9dce-945f4056783e)
We are using an ubuntu runner, creating a docker and then executing our tests.

Can someone help me on this? It started to happend yesterday without no reason. I didn't change nothing
