### ISSUE TITLE
Cypress.env returns undefined [Github Actions]

### ISSUE THREAD

**Issue by DarkendHall** [cypress-io/github-action#1155]
Like the title says I get undefined returned from Cypress.env() when running in Github Actions, but it works fine locally.

I have the following cypress.config.ts file

```ts
import { defineConfig } from "cypress";

export default defineConfig({
  e2e: {
    baseUrl: "http://localhost:3000",
    testIsolation: true,
    viewportHeight: 1024,
    viewportWidth: 1280,
  },
  env: {
    BACKEND_URL: "http://localhost:8080",
  }
});
```
and then I have a test which uses the backend to send a request as follows
```ts
cy.request(`${Cypress.env("BACKEND_URL") as string}/jobs?status=0`)
            .its("body")
            .should("have.length", 0);
```
Which should send a request to `http://localhost:8080/jobs?status=0`

This works fine locally, but when running it in Github Actions I get the following error when it reaches this test:

```
TypeError: Failed to parse URL from undefined/jobs?status=0
```

In addition to setting this environment variable in the config file I have also tried setting it in the workflow in the following places:

- env (prefixed with `CYPRESS_`)
- job.env (prefixed with `CYPRESS_`)
- job.step.env (prefixed with `CYPRESS_`)
- job.step.with.env

All of which results in the `Cypress.env(BACKEND_URL)` being undefined during the test.

I have also run the workflow with the `DEBUG` env vars set to `cypress:*` and can see that the env vars have been picked up by cypress see shorten log from github below

```
cypress:server:project project has config { env: { BACKEND_URL: 'http://localhost:8080', CACHE_FOLDER: '/home/runner/.cache/Cypress' }, baseUrl: 'http://localhost:3000', testIsolation: true, ...
```

Any help is greatly appreciated.

**Comment by MikeMcC399** [comment]
@DarkendHall 

Could you please post your workflow?

**Comment by MikeMcC399** [comment]
@DarkendHall 

At first view this does not look like it is a bug in Cypress GitHub Action. You identified that you are getting a TypeScript error

```text
TypeError: Failed to parse URL from undefined/jobs?status=0
```

and the environment variable is being passed to Cypress

```text
cypress:server:project project has config { env: { BACKEND_URL: 'http://localhost:8080', CACHE_FOLDER: '/home/runner/.cache/Cypress' }, baseUrl: 'http://localhost:3000', testIsolation: true, ...
```

I will take a deeper look, however I only work with TypeScript as an exception (all the examples in this repo are JavaScript), so it may take me a few more steps.

The Cypress.io team will usually only get involved if it is likely to be a bug and if there is a repo available to them to view the error.

There is also a Cypress technical community available on Discord where you might like to go to for help [![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord) (click on button).

**Comment by MikeMcC399** [comment]
@DarkendHall 

I was not able to reproduce your issue, using an environment variable defined in `cypress.config.ts` used in `cy.request()` and run with `cypress-io/github-action` so I can't suggest any solution.

If you are able to create a simple example where it fails and post it as a runnable GitHub repository we can take a look.

**Comment by DarkendHall** [comment]
> @DarkendHall
> 
> I was not able to reproduce your issue, using an environment variable defined in `cypress.config.ts` used in `cy.request()` and run with `cypress-io/github-action` so I can't suggest any solution.
> 
> If you are able to create a simple example where it fails and post it as a runnable GitHub repository we can take a look.

Thank you for your quick investigation, I will see if I can create a repo with it reproduced sometime tomorrow.

**Comment by DarkendHall** [comment]
I tried to export the URL of the server in e2e.ts and then import it into the test and experience the same issue with it resulting in being `undefined`

**Comment by MikeMcC399** [comment]
@DarkendHall 

I'm sorry to hear that you are continuing to have difficulties. If you believe that the Cypress GitHub Action is responsible for your problem and you can post a reproducible simple example, then we can progress further here.

**Comment by DarkendHall** [comment]
After reading the Github Actions log line by line I think thisis somehow related to Next.js and that it is responsible for the issue, will continue to investigate on my own during the day and comment what the problem was if I find it.

**Comment by DarkendHall** [comment]
It seems the issue was not related to cypress at all, but was the result of an unexpected difference in the build process with Next.js.

It didn't copy the `.env` files to the standalone build the same way it did on my machine because the script we run was not updated in the repo.

Thanks for your assistance @MikeMcC399!

**Comment by MikeMcC399** [comment]
@DarkendHall 

Congratulations on finding the source of your problem!
