### ISSUE TITLE
Cypress won't run correctly

### ISSUE THREAD

**Issue by jackguoAtJogg** [cypress-io/github-action#117]
I have been trying to figure this issue but still don't the cause. I simply updated a package dep and it works fine when I run cypress locally but on CI it would just errors out. I use the wait-on function and even it says the server is ready but it still cannot start the test. 
![image](https://user-images.githubusercontent.com/56273621/77485545-a4a0d500-6dea-11ea-87b9-7ff1ae5afeab.png)

**Comment by bahmutov** [comment]
Could you try again with the latest version of the GitHub Action?

**Comment by bahmutov** [comment]
Assuming the current version works
