### ISSUE TITLE
Thread setting is 2, but only 1 test suite(s) were found. Adjusting configuration accordingly. Weight file not found in path: cypress/parallel-weights.json

### ISSUE THREAD

**Issue by naveen1133** [cypress-io/github-action#1278]
Any idea on the below issue? 
PS E:\vista\vista> npm run test:parallel

> vista@0.1.0 test:parallel
> cypress-parallel -s 2 --spec "cypress/e2e/vista.cy.js,cypress/e2e/activity.cy.js"

1 test suite(s) found.
Thread setting is 2, but only 1 test suite(s) were found. Adjusting configuration accordingly.
Weight file not found in path: cypress/parallel-weights.json
npm error Missing script: "2"
npm error
npm error To see a list of scripts, run:
npm error   npm run
npm error A complete log of this run can be found in: C:\Users\N A V E E N\AppData\Local\npm-cache\_logs\2024-10-15T18_01_59_475Z-debug-0.log
┌─────────────────────────────────────────────────────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│ Spec                                                │ Time     │ Tests    │ Passing  │ Failing  │ Pending  │
├─────────────────────────────────────────────────────┼──────────┼──────────┼──────────┼──────────┼──────────┤
│ Results                                             │ 0s       │ 0        │ 0        │ 0        │ 0        │
└─────────────────────────────────────────────────────┴──────────┴──────────┴──────────┴──────────┴──────────┘
Found test suites does not match results.
Test suites found: 1
Test suite results: 0
Some test suites likely terminated without passing on results, exit with error
The following test suites are missing results: cypress/e2e/vista.cy.js,cypress/e2e/activity.cy.js

**Comment by MikeMcC399** [comment]
@naveen1133 

This is not the right repository for issues with `cypress-parallel`. We deal with `cypress-io/github-action` issues here.
