### ISSUE TITLE
Broken doc links to Cypress Cloud

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/github-action#1285]
## Issue

Running

```shell
npm run check:markdown
```

results in a report of 2 newly broken links in the [README](https://github.com/cypress-io/github-action/blob/master/README.md#specify-auto-cancel-after-failures) document:

  [✖] https://docs.cypress.io/guides/cloud/smart-orchestration#Auto-Cancellation → Status: 404
  [✖] https://on.cypress.io/guides/cloud/smart-orchestration/ → Status: 404

The broken links are in the sections:

- [Specify auto cancel after failures](https://github.com/cypress-io/github-action/blob/master/README.md#specify-auto-cancel-after-failures)
- [Parallel](https://github.com/cypress-io/github-action/blob/master/README.md#parallel)

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

This issue has been caused by restructuring https://docs.cypress.io.

Will you add redirects so that the old links work again?
If not, what should the links be changed to?

If there are any changes to these links to be made in this repo, it may make more sense for you to make them instead of splitting the work, which is why I took the liberty of assigning this issue to you in the first instance.

**Comment by jennifer-shehane** [comment]
Hmm, yah I thought this should work with this definition: https://github.com/cypress-io/cypress-documentation/blob/cy-conf-followups/netlify.toml#L1114 🤔  But this page has a specific overview it needs to route to now. I'll add a redirect.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

I'm not seeing any change to the error message so far:

  ERROR: 2 dead links found!

  209 links checked.
  [✖] https://docs.cypress.io/guides/cloud/smart-orchestration#Auto-Cancellation → Status: 404
  [✖] https://on.cypress.io/guides/cloud/smart-orchestration/ → Status: 404

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

## Suggestion

Add vanity links to https://on.cypress.io, for instance the following, and use them here:

- https://on.cypress.io/auto-cancellation
- https://on.cypress.io/smart-orchestration

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

- I submitted #1289 to resolve this issue without relying on any redirects.
