### ISSUE TITLE
pull_request vs push

### ISSUE THREAD

**Issue by jamime** [cypress-io/github-action#134]
> We recommend using the action with on: [push] instead of on: [pull_request] to get the most accurate information related to the commit on the dashboard.

In our project we will quickly max out our runners if we run each branch. Really, we only want the actions to run when someone submits their pull request.

If we use `pull_request` what difference will we see in the dashboard?

**Comment by jennifer-shehane** [comment]
@bahmutov I'm not sure this comment is accurate anymore since the services team merged fixes for recognizing Pull Request builds - it should be able to get the commit SHA for GitHub integration if the comment was referencing that. Maybe you're referring to some other functionality.

**Comment by coreylight** [comment]
I'm not sure if using `pull_request` is working for my project.
We currently use `push` but are switching to `pull_request`.
When using `push`, on the cypress dashboard each run has the title of the commit.
However, when using `pull_request` I see a title like:
`merge SHA into SHA`
And also the cypress check no longer seems to run correctly against the PR in question.
Anything we can do here?

**Comment by jennifer-shehane** [comment]
@coreylight The commit will show a title like `merge SHA into SHA`, this is autogenerated when pull request builds are made. This is expected

>And also the cypress check no longer seems to run correctly against the PR in question.

Can you clarify what you mean by `cypress check`? What is not running exactly? Are you referring to GitHub Integration to the Dashboard? Are you referring to the GitHub Action itself?

**Comment by coreylight** [comment]
@jennifer-shehane yes, by `cypress check` I mean the GH action itself
It seems to be stuck at `Expected — Waiting for status to be reported`

![CleanShot 2020-06-15 at 14 44 53](https://user-images.githubusercontent.com/1470090/84699235-c9eb3e00-af16-11ea-9945-cccaf1d2b844.png)

Happy to contribute to this repo if need be, just not sure where to start.

**Comment by MikeMcC399** [comment]
The original question was answered.

If there are any outstanding issues found in the current action version `@v6` please submit a new issue.
