### ISSUE TITLE
Upstream npm bug causing random failures

### ISSUE THREAD

**Issue by sarink** [cypress-io/github-action#136]
We're seeing this pretty frequently
```
npm ERR! syscall open
npm ERR! path /home/runner/work/web-alz/web-alz/node_modules/@babel/cli/node_modules/fsevents/node_modules/node-pre-gyp/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/runner/work/web-alz/web-alz/node_modules/@babel/cli/node_modules/fsevents/node_modules/node-pre-gyp/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```
I believe this is due to the npm bug: https://github.com/npm/cli/issues/558 and this action's use of `npm ci` https://github.com/cypress-io/github-action/blob/master/index.js#L215

**Comment by bahmutov** [comment]
Not sure why this happens, but we intend to keep `npm ci` command. If there is no reproducible example that specifically points at the mistake in the current code in this repo, closing this issue.
