### ISSUE TITLE
Targeting custom spec folder not working

### ISSUE THREAD

**Issue by stoplion** [cypress-io/github-action#140]
Hello,

What is the correct way to instruct action to find tests in custom folder?
I've tried several ways and am not able to target custom spec folder..

- Use `with.spec: "spec/cypress/integration/**/*"` and glob the folder with the test files
- Use `with.spec: "./spec/cypress/integration/**/*"` and glob the folder with the test files
- Use `with.integration-folder: "./spec/cypress/integration"`
- Use `with.integration-folder: "spec/cypress/integration"`
- Using a config file. `with.config-file: cypress.json` and have the `integrationFolder` defined there:
```
"integrationFolder": "spec/cypress/integration",
```

or 

```
"integrationFolder": "./spec/cypress/integration",
```
-----

With every method above, I'm **not** able to get the action to find the test files..

Most of the time it fails with this..
```
Can't run because no spec files were found.
We searched for any files inside of this folder:
/home/runner/work/CalciteApp/CalciteApp/cypress/integration
```
same result (concats app name together)
And does not look into `spec/cypress/integration`
With the setting `config-file: cypress.json` and 
```
{
  "baseUrl": "http://localhost:5000",
  "spec": "spec/cypress/integration/**/*",
  "defaultCommandTimeout": 10000,
  "projectId": "apwnwy"
}
```

**This one...**
`spec: spec/cypress/integration/**/*`
fails with ..
```
Can't run because no spec files were found.
We searched for any files matching this glob pattern:
spec/cypress/integration/**/*
```

_But there are_ spec files in `spec/cypress/integration/**/*`.

**Comment by bahmutov** [comment]
Can you describe the folder structure, please? Is it

```
root/
  cypress.json
  spec/
    cypress/
      integration/        
  .github/
    workflows/
      ci.yml 
```

In that case your cypress.json should have integration folder

```json
{
  "integrationFolder": "spec/cypress/integration"
}
```

I don't think you can pass `spec` via `cypresss.json` anyway (https://on.cypress.io/configuration), you can pass it via `with.spec`

**Comment by stoplion** [comment]
```
./spec
├── cypress
│   ├── cypress_helper.rb
│   ├── factories
│   ├── fixtures
│   ├── integration
│   ├── plugins
│   └── support
├── cypress.json
```

`./spec` is proj root

**Comment by bahmutov** [comment]
and working directory does not work? https://github.com/cypress-io/github-action#working-directory

**Comment by stoplion** [comment]
Ughh 🤦 I've figured it. Closing..

There is an empty `cypress.json` at root level, _and_ a `cypress.json` in `/spec`. Maybe the setup script created on at root level and I didn't notice it.
