### ISSUE TITLE
Cannot run a simple test on Windows

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/github-action#148]
Getting an error in https://github.com/bahmutov/try-cra-app-typescript/pull/10

<img width="1439" alt="Screen Shot 2020-05-28 at 9 44 28 AM" src="https://user-images.githubusercontent.com/2212006/83149417-0968fc00-a0c8-11ea-8f1d-6fd45fbb937a.png">

Hmm, the current directory is incorrect?!

**Comment by MikeMcC399** [comment]
This is a stale issue and there is not enough information to judge whether it still occurs on current versions.
