### ISSUE TITLE
replace @octokit/rest with @octokit/core

### ISSUE THREAD

**Issue by gr2m** [cypress-io/github-action#151]
Hey friends,

@octokit maintainer here 👋 

It looks like you only use the `octokit.request` method

https://github.com/cypress-io/github-action/blob/345747a85e46d21addb1f8bc23116b9eefdcf41a/index.js#L386-L410

In that case, I would recommend to use [`@octokit/core`](https://github.com/octokit/core.js) instead of [`@octokit/rest`](https://github.com/octokit/rest.js/) - the latter just adds ~600 convenience methods for every REST API endpoint. There will also be fewer deprecations & breaking changes with `@octokit/core`. 

The only change you would need is

```diff
- const { Octokit } = require('@octokit/rest')
+ const { Octokit } = require('@octokit/core')
```

I'd be happy to send a pull request myself

**Comment by jennifer-shehane** [comment]
@gr2m That'd be great! We would welcome a PR.
