### ISSUE TITLE
support multiple `wait-on` values

### ISSUE THREAD

**Issue by a7madgamal** [cypress-io/github-action#152]
I'm trying to wait for multiple servers (aka ports) before running the test, is this possible?

**Comment by platy** [comment]
The solution I came up with was adding new parameters `start2` and `wait2` - not particularly elegant but it's doing the trick at the moment.

If you want to use it, the forked action is `chargery/cypress-io-github-action@f15bca7`.

The changes : https://github.com/chargery/cypress-io-github-action/commit/f15bca7bee6c43ccc801c72b355e616fe566ccdb

**Comment by bahmutov** [comment]
I would refactor `wait-on` and `start` into accepting a comma-separated list, and the adding support for starting each process, and then waiting for each URL one by one. Something like

```
start: npm start, npm run api
wait-on: http://localhost:3000,http://localhost:5000
```

**Comment by platy** [comment]
Great! That does seem nicer
