### ISSUE TITLE
Action.yml is missing `runTests` input

### ISSUE THREAD

**Issue by lukaw3d** [cypress-io/github-action#157]
GitHub shows a warning `Unexpected input 'runTests', valid inputs are [...` when using runTests to split install and tests

https://github.com/cypress-io/github-action/blob/ae198975d84aaea525e6173db18d37fd28a284ee/README.md#L710-L712

**Comment by jennifer-shehane** [comment]
@lukaw3d Can you provide your github action configuration that caused this error? Thanks!

**Comment by lukaw3d** [comment]
Here's an example, made out of examples/basic: https://github.com/lukaw3d/try-github-actions/commit/d7def2ed5ce72de334ad428e897c278e786dacaa

Corresponding warnings: https://github.com/lukaw3d/try-github-actions/actions/runs/130060807

![warnings](https://user-images.githubusercontent.com/3758846/84180269-8791af00-aa87-11ea-9658-ba6e5e38600c.png)

**Comment by bahmutov** [comment]
Yes, `runTests` is missing from the parameters in https://github.com/cypress-io/github-action/blob/master/action.yml and I would welcome a pull request to add it
