### ISSUE TITLE
Using `await cy.url()` works with `cypress open` but fails with `cypress run`

### ISSUE THREAD

**Issue by Vadorequest** [cypress-io/github-action#160]
Using `cypress open`:

![image](https://user-images.githubusercontent.com/3807458/84814714-28491700-b012-11ea-9721-4806c4f77978.png)

Using `cypress run`:

![image](https://user-images.githubusercontent.com/3807458/84814848-5c243c80-b012-11ea-8f21-1c249832d720.png)

Test:
```js
const baseUrl = Cypress.config().baseUrl;

describe('Index page', async () => {
  /*
  * Visits the page before each test
  */
  beforeEach(() => {
    cy.visit('/');
  });

  it('should be running on the right domain', async () => {
    const url = await cy.url();
    cy.log(`Expected to be running on:`);
    cy.log(baseUrl);
    cy.log(`Actually running at:`);
    cy.log(url);
    cy.url().should('contains', baseUrl);
  });
});
```

I don't get why it times out when running in the CLI. This seems odd.

**Comment by bahmutov** [comment]
please don't use `async / await` since it won't run as you expect. Read our introduction to Cypress commands, especially async part.

**Comment by Vadorequest** [comment]
Indeed, using .then worked properly.
