### ISSUE TITLE
Github Action passes when Cypress tests fail

### ISSUE THREAD

**Issue by trevorgerhardt** [cypress-io/github-action#168]
We've seen inconsistent behavior when using the Cypress Github Action. Sometimes when the Cypress tests fail, the Github Action still gets a passing status. (As seen here: https://github.com/conveyal/analysis-ui/pull/1119/checks?check_run_id=788129189#step:9:2851 -- note: you may need to scroll to the bottom).

This may very well be user error by me. Is there configuration that I do not know about to ensure that Cypress failure should indicate action failure?

**Comment by albingroen** [comment]
Same happening for me. Seems to kind of defeat the purpose of this action almost... Especially when just glancing at the result in a pr. It says the action was successful, but if you check the test might not actually have succeeded. Can someone take a look at this? I might also have missed some configuration here, but if that's the case please let us know 😅

**Comment by albingroen** [comment]
Maybe @bahmutov can take a look at this?

**Comment by jennifer-shehane** [comment]
Could you try to run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here when this fails to exit properly?

**Comment by bahmutov** [comment]
My bad - the v2 `runTests` function returns the number of failed tests, should have rejected instead.

https://github.com/cypress-io/github-action/blob/8d2343f2e997700d96b7dd320da79246034f96e7/index.js#L572

**Comment by zachrattner** [comment]
Is anyone else seeing this come up again on the latest Cypress 9.5.0? Github Actions show test pass even if the test fails.

**Comment by kumarajiv1** [comment]
Hi @zachrattner , same here. Did you find any solution to it?

**Comment by zachrattner** [comment]
@kumarajiv1 We stopped using Cypress over this, but it's possible they have come up with a fix since then.
