### ISSUE TITLE
Newly added parameter `--quiet` is not using in CI

### ISSUE THREAD

**Issue by DlgSHi** [cypress-io/github-action#172]
I've updated `cypress` version to `4.9.0`, added `--quiet` parameter to the CI build (we are using `GitHub Actions`) but this parameter wasn't passed to `npx cypress run...` as on screenshot below: 

<img width="778" alt="Screenshot 2020-06-29 at 09 30 28" src="https://user-images.githubusercontent.com/34001198/85980652-7cc59c80-b9eb-11ea-9160-82733efb1856.png">

Link to the changed `yml` [file](https://github.com/Sage/carbon/pull/3027/files)
Link to the [build](https://github.com/Sage/carbon/runs/817429740?check_suite_focus=true)

**Comment by bahmutov** [comment]
Yes, this flag needs to be added to action.yml as you did in https://github.com/cypress-io/github-action/pull/171 but also it needs to be read from the action's inputs and passed to Cypress. Can you extend the PR and update:

- https://github.com/cypress-io/github-action/blob/605c2c6d717db544c723e3c492d01bc913a028f8/index.js#L364
- https://github.com/cypress-io/github-action/blob/605c2c6d717db544c723e3c492d01bc913a028f8/index.js#L478
- make sure to build the `dist` folder too!
- add YML file with example https://github.com/cypress-io/github-action/tree/master/.github/workflows and link it to the README like other examples

**Comment by DlgSHi** [comment]
> Yes, this flag needs to be added to action.yml as you did in #171 but also it needs to be read from the action's inputs and passed to Cypress. Can you extend the PR and update:
> 
> * https://github.com/cypress-io/github-action/blob/605c2c6d717db544c723e3c492d01bc913a028f8/index.js#L364
> * https://github.com/cypress-io/github-action/blob/605c2c6d717db544c723e3c492d01bc913a028f8/index.js#L478
> * make sure to build the `dist` folder too!
> * add YML file with example https://github.com/cypress-io/github-action/tree/master/.github/workflows and link it to the README like other examples

updated

**Comment by bahmutov** [comment]
Fixed in https://github.com/cypress-io/github-action/releases/tag/v2.2.0
