### ISSUE TITLE
Action won't re-run if ci-build-id is set like in documentation

### ISSUE THREAD

**Issue by nitzanashi** [cypress-io/github-action#177]
> You can overwrite ci-build-id used to link separate machines running tests into a single parallel run

`ci-build-id: '${{ github.sha }}-${{ github.workflow }}-${{ github.event_name }}'`

if tests are failing or we just want to rerun them this won't work since the `ci-build-id` is with the same as previous one.
Is there an option to solve this issue?

**Comment by jennifer-shehane** [comment]
The ci-build-id needs to be unique between the initial run and the rerun. You might reference https://medium.com/attest-engineering/adding-a-unique-github-build-identifier-7aa2e83cadca on how to ensure this ID is unique between an initial run and a rerun.
