### ISSUE TITLE
Have just a few main examples in README and move the full list

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/github-action#20]
Like https://github.com/cypress-io/circleci-orb does it

<img width="460" alt="Screen Shot 2019-11-14 at 11 45 28 AM" src="https://user-images.githubusercontent.com/2212006/68877580-4d6c5480-06d4-11ea-9f3a-863fa3d8f6ee.png">

**Comment by MikeMcC399** [comment]
It's unclear exactly what was meant in this old issue and https://github.com/cypress-io/circleci-orb doesn't look like the screenshot. I suggest to close this issue.
