### ISSUE TITLE
socket hang up

### ISSUE THREAD

**Issue by stolinski** [cypress-io/github-action#203]
Hi,
We're seeing `socket hang up` and a failing load of cypress on GH Actions. All tests and flow are working fine on local, but this issue is causing our builds to fail. Any thoughts?

**Comment by jbelien** [comment]
Same issue here: https://github.com/HackYourFutureBelgium/hackyourfuture.be/pull/25/checks?check_run_id=1217390243

**Comment by bahmutov** [comment]
Try using the latest version of this GH action, the ping and retry logic was recently updated and tested.

**Comment by jbelien** [comment]
What's the version number of the latest version ?
If I go to https://github.com/marketplace/actions/cypress-io it says `v1.16.1` but I see there is a `v2.3.10` tag.

Should I stay on `v1.16.1` or should I go to `v2.3.10` ?

**Comment by bahmutov** [comment]
Very weird - I see the GitHub Marketplace showing old version, but we have so many releases after that

https://github.com/cypress-io/github-action/releases

Please use version release from the repo, I will try to find how to update the Marketplace tag

**Comment by jbelien** [comment]
It indeed seems to be fixed 👍 
Thanks a lot :)
