### ISSUE TITLE
Deprecation warning - set-env

### ISSUE THREAD

**Issue by adam-remotesocial** [cypress-io/github-action#206]
When using the Cypress GitHub Action, The build outputs the following lines in the log:

```
Warning: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Warning: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

**Comment by gherkins** [comment]
maybe just updating `@actions/core` to 2.* would be enough:
https://github.com/cypress-io/github-action/blob/6998a7cfff76c58615c7563d2405b6b111abb6e7/package.json#L32

see https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by eliasplatekdkt** [comment]
the auto-merge doesn't work, either github actions crashed unexpectedly, or the upgrade breaks the action

https://github.com/cypress-io/github-action/runs/1195334337?check_suite_focus=true

**Comment by Kocal** [comment]
@eliasplatekdkt how is this related to this issue?

**Comment by eliasplatekdkt** [comment]
The error is related to the PR updating actions to 1.2.6, and is currently failing.

https://github.com/cypress-io/github-action/pull/205

I'm not related to the project, I was just adding some context for someone who could work on it

**Comment by Kocal** [comment]
Oh! I'm sorry. I thought it was a checks suite from one of your repo, not from a PR of this repository. 😥

**Comment by eliasplatekdkt** [comment]
@Kocal no worry :) 

the error looks like a timeout occured during the build, I am currently having a lot of errors on the github runners recently so I would not be surprised that this error is just a false positive.
