### ISSUE TITLE
`config` parameter is not overriding the `cypress.json` configuration file

### ISSUE THREAD

**Issue by madiodio** [cypress-io/github-action#207]
Hey there, first would love to say this action is awesome 👍🏾.

I have a little annoyance right now with this action. It doesn't seem possible to set the configuration options directly from the `config` parameter (specified in the [readme](https://github.com/cypress-io/github-action#config)) that will override values on the `cypress.json` file. 

I have reproduced this behavior on the repo below to showcase this problem:

- https://github.com/madiodio/cypress-gh-action-config-bug

This use case is pretty simple. I have the `3000` port on local development but `5000` on a production build. Therefore I need to set up the `5000` port directly on this action config parameter that should override the `baseUrl` option on the `cypress.json` configuration file but that is not working. The `3000` port is still getting picked up when the workflow is running thus failing the tests :(.

Question: Is this how it's supposed to work ? What other options/alternatives do I have to make the use case works as expected without having to resort to adopt a single port for both builds ?

Update: Specifying the `config-file` parameter still doesn't override the cypress.json root configuration file, you can check this on the [reproduction repo](https://github.com/madiodio/cypress-gh-action-config-bug/tree/config-file-test-case)

**Comment by tamipangadil** [comment]
You mentioned that this was already fixed but it was not. It is still happening on the latest version where we couldn't override the value of `baseUrl` from `cypress.json` file in our GitHub action 
```
   env:
      CYPRESS_BASE_URL: "http://localhost:3000"
   with: 
       config: baseUrl="http://localhost:3000"
```

It still picking up the value from `cypress.json` regardless of the settings there

**Comment by MikeMcC399** [comment]
@sauldeleon 

> Added a config parameter in the github action to override the cypress.config.ts file parameter, and its not being taken into account :(

Please open a new issue and post your workflow `*.yml` file.

**Comment by sauldeleon** [comment]
Hello @MikeMcC399 thanks for the response. I will do as you said. Sorry for the noise! Thanks!

**Comment by MikeMcC399** [comment]
This issue is covered in the documentation:

[command](https://github.com/cypress-io/github-action#custom-test-command):

> **Caution**: using the action parameter `command` causes multiple other parameters to be ignored including: `auto-cancel-after-failures`, `browser`, `ci-build-id`, `command-prefix`, `component`, `config`, `config-file`, `env`, `group`, `headed`, `parallel`, `project`, `publish-summary`, `quiet`, `record`, `spec` and `tag`.
