### ISSUE TITLE
Use action with Cypress installed in another directory

### ISSUE THREAD

**Issue by pvtri96** [cypress-io/github-action#21]
Hi,

I have a cypress installed inside a mono repository directory (e.g.: [my repository](https://github.com/penta-jelly/re-radio)). How can I config my workflows with this action to be able to run cypress?

Many thanks.

**Comment by bahmutov** [comment]
Why do you need to do apt-update and install here? https://github.com/penta-jelly/re-radio/blob/master/.github/workflows/test.yml#L24

**Comment by pvtri96** [comment]
> Why do you need to do apt-update and install here? [penta-jelly/re-radio:.github/workflows/test.yml@`master`#L24](https://github.com/penta-jelly/re-radio/blob/master/.github/workflows/test.yml#L24) [](/penta-jelly/re-radio/blob/HEAD@{2019-11-16T18:49:07Z}/.github/workflows/test.yml#L24)

It is a copy-pasta code, I was using Travis before and followed the [guide](https://docs.cypress.io/guides/guides/continuous-integration.html#Example-travis-yml-config-file) on official Cypress document. Then I moved to Github action and I think that Github action may require the same configuration. Do I actually have to install it?

**Comment by bahmutov** [comment]
Nope, you don't - GitHub Linux environment is already set up pretty well, nothing to do, see examples in this repo's README and in https://github.com/bahmutov/cypress-gh-action-example

**Comment by pvtri96** [comment]
Thank for your fast feedback, I will remove that step ASAP! Back to the point where I am installing and running Cypress in another directory, do you have any recommendation?

**Comment by bahmutov** [comment]
I did not add parameter for current working directory during cypress test command but you can look at the actions code to see how to do it

**Comment by bahmutov** [comment]
for your use case, see https://github.com/cypress-io/github-action#split-install-and-tests
