### ISSUE TITLE
Error: getCacheEntry failed: No scopes with read permission were found on the request.

### ISSUE THREAD

**Issue by igorpan** [cypress-io/github-action#212]
Hi, we haven't made any changes to our build process, but our Cypress github-action started failing today.

Output:

```
Run cypress-io/github-action@v2
  with:
    working-directory: cypress-tests
    record: false
    config-file: cypress.json
Error: getCacheEntry failed: No scopes with read permission were found on the request.
```

cypress.json

```
{
  "baseUrl": "...",
  "projectId": "...",
  "retries": 2,
  "video": false
}
```

Since the error mentions cache I've attempted: 
* Re-running the workflow
* Adding a new commit (assuming it might bust the cache)
* Closing and re-opening a different PR that workflow was tied to 

Nothing helped, and the error stayed the same.

**Comment by redian** [comment]
Any update on this, we are seeing the same thing too:
![Screenshot 2020-10-26 at 08 56 37](https://user-images.githubusercontent.com/816941/97152701-31d54f00-1769-11eb-84b3-9399d4c739e2.png)

**Comment by redian** [comment]
Could this be related to these changes? `https://github.com/cypress-io/github-action/commit/5761360df684dbd09006fad068bbdafd6b06cb63` possibly affecting opened PRs like mine before this had gone through onto `cypress-io/github-action@v2`?

**Comment by bahmutov** [comment]
Interesting.

Yes, the commit https://github.com/cypress-io/github-action/commit/5761360df684dbd09006fad068bbdafd6b06cb63 finally has switched to using official https://github.com/actions/cache module to interact with GitHub Actions cache. I did not see anything in their docs about cache read permissions, but I think it is possible there is something about the event (your workflow fails here for a deploy event, right?) that does not give access to caching.

Seems this is a known issue for them: https://github.com/actions/cache/issues/380 and https://github.com/actions/cache/issues/297

## Workarounds

- use the previous explicit version of this action, from https://github.com/cypress-io/github-action/tags I see `2.2.7` is the last tag
 
<img width="567" alt="Screen Shot 2020-10-26 at 9 30 36 AM" src="https://user-images.githubusercontent.com/2212006/97178483-ea9d8d00-176d-11eb-96c5-1c7f5bcb830c.png">

```yml
- name: Cypress run
  uses: cypress-io/github-action@v2.2.7
```

## Solution

Let me add `.catch` and ignore the failure from restoring the cache and if it works with the example from https://glebbahmutov.com/blog/develop-preview-test/ in repo https://github.com/bahmutov/eleventy-example then it will be a good solution in general

**Comment by bahmutov** [comment]
I see the same error in https://github.com/bahmutov/eleventy-example/actions/runs/329190071

<img width="1027" alt="Screen Shot 2020-10-26 at 9 51 58 AM" src="https://user-images.githubusercontent.com/2212006/97180816-ed4db180-1770-11eb-8e80-bc9d3f35b1ba.png">

**Comment by redian** [comment]
Thank you @bahmutov 👍
