### ISSUE TITLE
wait-on never completes if socket hangs

### ISSUE THREAD

**Issue by RomanHotsiy** [cypress-io/github-action#228]
I use this with gatsby and it looks like when gatsby starts it sets up the server immediately which hangs the socket (maybe it's related to some specific setup I use). The server answers later.

Looks like `ping` function needs a timeout to be added to `got`:

E.g.

```js
/**
 * A small utility for checking when an URL responds, kind of
 * a poor man's https://www.npmjs.com/package/wait-on
 */
const ping = (url, timeout) => {
  const start = +new Date()
  return got(url, {
    timeout: 1000, // <======== here
    retry: {
      retries(retry, error) {
        const now = +new Date()
        core.debug(
          `${now - start}ms ${error.method} ${error.host} ${
            error.code
          }`
        )
        if (now - start > timeout) {
          console.error('%s timed out', url)
          return 0
        }
        return 1000
      }
    }
  })
}
```

**Comment by TatsumiSuenaga** [comment]
We use Gatsby as well and that may be the issue

**Comment by RomanHotsiy** [comment]
Yes. It started happening recently without any changes on our side.
Suddenly action runs started to take forever. Hopefully, I noticed it and it didn't cost us a lot. But we've got a few builds stuck for more than 4 hours 🙀

**Comment by TatsumiSuenaga** [comment]
Sounds exactly like what happened to us. A couple dependabot PRs ran for hours and killed our monthly minutes 😅

**Comment by bahmutov** [comment]
Could you try new release https://github.com/cypress-io/github-action/releases/tag/v2.3.9 where I have bumped `got` and reworked the `ping`, please?

**Comment by jrparish** [comment]
`2.3.9` actually broke us. Specifying `2.3.8` works fine though. 

![image](https://user-images.githubusercontent.com/5173987/99122198-7fecae00-25c3-11eb-892c-661026d22013.png)

**Comment by bahmutov** [comment]
Can you run with debug logs on? Is this Webpack Dev server timing out? Can you provide a reproducible example I can run?

**Comment by RomanHotsiy** [comment]
@bahmutov the new release fixed the issue! Thanks for the quick turnaround 🙌

**Comment by bahmutov** [comment]
Super
