### ISSUE TITLE
How to handle reports an error

### ISSUE THREAD

**Issue by zhanchangchen** [cypress-io/github-action#229]
Cypress test command: npx cypress run --config-file cypress.json --env false

Error: The `set-env` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Cypress test command: npx cypress run --config-file cypress.json --env false

Error: The `set-env` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
/usr/local/bin/npx cypress run --config-file cypress.json --env false

**Comment by bahmutov** [comment]
What version of this action are you using, since we have replaced set-env?

**Comment by zhanchangchen** [comment]
my version： 'cypress-io/github-action@v1.16.1' Latest version

https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands

**Comment by raresserban** [comment]
So I guess the fix is to use v2, which is actually this fork repository?
https://github.com/bastihav/github-action
This is what worked for me but really don't know the differences between the two.

**Comment by bahmutov** [comment]
Please switch to the latest release which has the fix for `set-env` https://github.com/cypress-io/github-action/releases
