### ISSUE TITLE
set-env has been deprecated for github actions. Causing error in action

### ISSUE THREAD

**Issue by VampSlayer** [cypress-io/github-action#240]
![image](https://user-images.githubusercontent.com/13288333/99572749-068efa00-29cd-11eb-93c6-38cd817302cd.png)
In my github action I am getting all tests as failing even tho they have passed.
I checked the logs and look like the trying to use 'set-env' has been disabled and causing an Error. 

https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Does anybody know about this?

**Comment by bahmutov** [comment]
Could you try the latest v2 version of the action, we have upgraded `set-env` to the new API.

**Comment by VampSlayer** [comment]
Thank you! I look through the docs just then again and saw,.

Hahah. READ THE DOCS.
