### ISSUE TITLE
README Examples are unclear on how Cypress system requirements get installed

### ISSUE THREAD

**Issue by slaweet** [cypress-io/github-action#251]
Based on basic example it's https://github.com/cypress-io/github-action/blob/master/README.md#basic I don't understand how installing  https://docs.cypress.io/guides/getting-started/installing-cypress.html#System-requirements (e.g. `apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb`) should be handled.

I don't think that all those packages are installed out-of-the-box when using `runs-on: ubuntu-16.04`. Given there is no mention of it in the docs, I'd assume it's something that this action is taking care of. But that doesn't happen when I try to use it on a Github Enterprise instance. 

Please note that I'm only starting to get familiar GitHub actions, so my problem is most likely due to my lack of understanding of something. If this is the case, I'm sure there will be other people like me that would benefit from the README explaining the missing part. I don't really know what the missing part is, I just know that with the README as is I was not able to run this GitHub action on a GitHub Enterprise instance due to the following error
```
/home/runner/.cache/Cypress/3.8.3/Cypress/Cypress: error while loading shared libraries: libXtst.so.6: cannot open shared object file: No such file or directory
```

**Comment by bahmutov** [comment]
Take a look at https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-basic.yml - we test Cypress v6 on all Ubuntu versions, and it seems the virtual environments already have all Cypress OS dependencies installed. I will add a shot comment about it.
