### ISSUE TITLE
What's the value of the default `cache-key` that's being applied?

### ISSUE THREAD

**Issue by Vadorequest** [cypress-io/github-action#267]
I'm not sure about the default `cache-key` value, if none is provided. Is there any?

Also, since what version is `cache-key` available? I couldn't figure it out exactly.

Also, it wasn't obvious to me that using `cypress-io/github-action@v2` would point to the [v2 branch](https://github.com/cypress-io/github-action/tree/v2) (I looked for tags/releases and couldn't find it), I don't know if that can be made clearer in the doc.

**Comment by bahmutov** [comment]
You can find the cacke key logic in https://github.com/cypress-io/github-action/blob/f4a8f15c84aebbe43b9f3647072456b240d1e2f6/index.js#L132-L186

You can see what it does by turning on the debug logs https://github.com/cypress-io/github-action#debugging

Not sure how to describe `v2` better, there is already a documentation section here https://github.com/cypress-io/github-action#explicit-version

**Comment by Vadorequest** [comment]
@bahmutov Thank you very much!

Do you know if there is anything obvious we can do to improve how fast Cypress runs on CI? We tried using the cache-key but I feel like it's properly applied by default, so I'm not sure if we can improve anything more.

**Comment by bahmutov** [comment]
You mean speeding up the installing step?

**Comment by Vadorequest** [comment]
Yeah, it takes 3mn to run the whole cypress, wonder if that can be sped up.
