### ISSUE TITLE
CYPRESS_CACHE_FOLDER not being used

### ISSUE THREAD

**Issue by MartijnHols** [cypress-io/github-action#269]
The env var `CYPRESS_CACHE_FOLDER` according to [the docs](https://docs.cypress.io/guides/getting-started/installing-cypress.html#Environment-variables) "Changes the Cypress binary cache location". This value is not being used by the action, providing no way to customize the cache location. This makes it harder to cache the Cypress binary in a separate GitHub action step since not all caching methods or actions allow caching a directory from the home folder. An example of such an action would be [upload-artifact](https://github.com/actions/upload-artifact), which can be used to install dependencies in a single job instead of having to do it repeatedly in every job.

**Comment by bahmutov** [comment]
closed by #253
