### ISSUE TITLE
Running tests on self-hosted runners 

### ISSUE THREAD

**Issue by petar-spasov** [cypress-io/github-action#287]
Has anyone been able to run tests on self-hosted runners with firefox and chrome ? I tried to find references in the documentation but most of the examples are Github-Hosted.

**Comment by bahmutov** [comment]
Does it make any difference? Is it not working?

**Comment by petar-spasov** [comment]
There were some issues with finding the browsers, but it was something wrong with out configuration so we fixed it. The issue can be closed. Thanks for the response. :)
