### ISSUE TITLE
Response code 404 (Not Found) when Vite app is successfully running.

### ISSUE THREAD

**Issue by bluebill1049** [cypress-io/github-action#293]
Hi,

I am trying to migrate from [CRA](https://github.com/facebook/create-react-app) to [Vite](https://github.com/vitejs/vite)

However, I am encountering an issue with running the app within the cypress GitHub action.

here is a screenshot of the issue

<img width="693" alt="Screen Shot 2021-02-08 at 7 48 53 pm" src="https://user-images.githubusercontent.com/10513364/107196393-ae551a80-6a46-11eb-91e2-8cdaad01fd4f.png">

PR: https://github.com/react-hook-form/react-hook-form/pull/4132

More Context: 

- nothing else is changed at the config level, except switch from CRA to Vite.
- running it locally is fine.

<img width="1407" alt="Screen Shot 2021-02-08 at 8 01 00 pm" src="https://user-images.githubusercontent.com/10513364/107197737-66cf8e00-6a48-11eb-9063-5cc6b66a9613.png">

- standard action script

```
name: E2E Test

on: [pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          DEBUG: 'cypress:*'
        with:
          start: npm run start:app
          wait-on: 'http://localhost:3000/'
          wait-on-timeout: 60
```

**Comment by bahmutov** [comment]
I think this is the same issue as https://github.com/bahmutov/start-server-and-test/issues/294 which just needs Accept header update. I will take a look, thanks for providing a link to the reproducible example

**Comment by bluebill1049** [comment]
Amazing! thanks very much for the fix @bahmutov ❤️
