### ISSUE TITLE
Push to codecov after success

### ISSUE THREAD

**Issue by ddelange** [cypress-io/github-action#301]
Hi,

Landed here because of https://about.codecov.io/resource/ship-safer-code-with-cypress-and-codecov/.

How to push the frontend coverage from cypress to codecov upon success of this action?

**Comment by bahmutov** [comment]
The example repo https://github.com/bahmutov/cypress-realworld-app from the webinar used CircleCI to run E2E tests and pushed code coverage using Codecov Orb. If you want to run tests on GitHub Actions you can use their https://github.com/codecov/codecov-action to easily push the coverage to Codecov service. I think it would be something like this:

```
- uses: cypress-io/github-action@v2
- uses: codecov/codecov-action@v1
```

See their action's README for all parameters
