### ISSUE TITLE
verified github action

### ISSUE THREAD

**Issue by achan-godaddy** [cypress-io/github-action#305]
Would it be possible to get the [verified ](https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions) status for this action on github?  This could help us adopt this because some enterprise organizations require this certification.

**Comment by el7cosmos** [comment]
I need this, as our organization require verified creator for Github action

**Comment by perkam** [comment]
Seconded - our organization also requires all actions to be verified by GitHub. It would enable us to use this awesome work :)

**Comment by jennifer-shehane** [comment]
We've put in a request to GitHub to become a verified publisher. If approved, the action will show up as verified. So now we wait.

**Comment by perkam** [comment]
@jennifer-shehane That is great to hear. Thank you for taking care of this :)

**Comment by dhaval-vithalani** [comment]
@jennifer-shehane Any updates on this !!

**Comment by jaffrepaul** [comment]
Closing this issue as Cypress is a verified publisher.

![Screen Shot 2023-02-27 at 5 57 09 PM](https://user-images.githubusercontent.com/6298501/221707550-0a2ba24e-5824-44f9-9a23-3ad9ad8bd838.png)
