### ISSUE TITLE
Action hangs running on Windows/Edge

### ISSUE THREAD

**Issue by felippepuhle** [cypress-io/github-action#316]
I'm not sure why, but it happens pretty often. We've tried a bunch of things (using different images included) but we were not able to solve this issue. We had to set a `timeout-minutes` on our workflow, otherwise if it happens the action would run forever until manually canceled.

![Screen Shot 2021-03-11 at 9 34 37 AM](https://user-images.githubusercontent.com/15961929/110788878-f5a11780-824d-11eb-9afd-217eb0b60c10.png)

The logs don't have any useful information:

![Screen Shot 2021-03-11 at 9 43 25 AM](https://user-images.githubusercontent.com/15961929/110789080-40bb2a80-824e-11eb-97b5-31426e500e84.png)

As far as we can notice for some reason after finishing that last test(it's kinda random, it's not always the same test) nothing happened for 9min until the operation timed out and got canceled. The same test suite is running fine on Linux machines, testing with Chrome and Firefox.

Any tips here? Thanks so much!

**Comment by Tooluloope** [comment]
Having this same issue

**Comment by alessioerosferri** [comment]
Having same issue on ubuntu too

**Comment by MikeMcC399** [comment]
Is this issue still happening with current versions?

GitHub [window-2022](https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md#browsers-and-drivers) (latest) currently bundles Microsoft Edge 108.0.1462.46. Same for the GitHub Ubuntu runners.

I have run `cypress-io/github-action@v5` on `ubuntu-20.04`, `windows-latest` & `macos-latest` with Cypress 9.6.1 and 10.0.0 against the Microsoft Edge browser and I did not see any problem.

**Comment by felippepuhle** [comment]
TBH I'm not using Cypress anymore as I've been focusing on React Native lately - should we just close this issue then?

**Comment by MikeMcC399** [comment]
@felippepuhle 

Thanks for responding! There haven't been any more comments in this issue for almost a year, and if the issue is not relevant to you any more then closing it would be the best.

**Comment by felippepuhle** [comment]
Sounds good, thanks!
