### ISSUE TITLE
Notify Cypress Dashboard when action is cancelled in GitHub

### ISSUE THREAD

**Issue by donnacello** [cypress-io/github-action#322]
When a test run is cancelled via GitHub actions, the Cypress Dashboard continues wait 90 minutes before it ends with a Timeout status. If the test is manually cancelled in the dashboard after the cancellation in GitHub, it seems to continue indefinitely --been more than 2 days now... 
Here is a screenshot of a test run:
![image](https://user-images.githubusercontent.com/20868683/111549462-1256c580-87e1-11eb-902e-6db6fd851110.png)

**Comment by hkarambizi** [comment]
It would appear that this is caused by an [incident](https://www.cypressstatus.com/incidents/ct0tcqq6dxmx) which was reported by other users during this specific time period. Our Engineers are investigating the issue causing the indefinite runs.

We apologize for the inconvenience.

As an additional resource, you can monitor our status or review any outages at https://status.cypress.io/

**Comment by donnacello** [comment]
Thanks @hkarambizi 
That incident seems to have caused our tests to continue to run after the GitHub actions have completed. 
The status update indicates this has been resolved and our tests have concluded, normally they should be done by 3-4 minutes:
![image](https://user-images.githubusercontent.com/20868683/111563805-843d0800-87fd-11eb-8990-84b96274aa0a.png)
One of our "cancelled" tests still seem to be stuck and it's an hour away towards a 3-day run
![image](https://user-images.githubusercontent.com/20868683/111564246-47bddc00-87fe-11eb-82b8-73c407a166c4.png)

**Comment by donnacello** [comment]
Hi @hkarambizi , I see yourovide more infor email but I do not think you are receiving any of my responses. Would you be able to confirm this please? Is there any other platform where we can discuss this? Happy to provide more information on this

**Comment by donnacello** [comment]
The problem we are encountering is:
**if a GitHub action (that triggers cypress tests) is cancelled, the Cypress Dashboard does not recognise that the test run has been cancelled and it continues to run for 90 minutes**

Can something be added to the cypress github action that, when cancelled, notifies the Cypress Dashboard to stop waiting for test results? If not, can there be away to _instead_ at least shorten the 90 minute timeout for Cypress Dashboard not GitHub.

**Comment by bahmutov** [comment]
So the Dashboard keeping the run opened for 90 minutes should not cause a problem, eventually it times out. But we have also added a feature to our Dashboard to cancel runs https://on.cypress.io/smart-orchestration - when you click Cancel on the dashboard it returns "stop what you are doing next and exit" API response to each Cypress instance.
