### ISSUE TITLE
Confirm the custom cache key works correctly

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/github-action#339]
Seems after changing the key it still has restored an old cache?

![Screen Shot 2021-03-31 at 3 35 06 PM](https://user-images.githubusercontent.com/2212006/113200781-c40ce200-9236-11eb-9cef-84d0f620e9c0.png)

project https://github.com/cypress-io/cypress-and-jest-typescript-example

**Comment by tsposato** [comment]
Is there also a way to 'refresh' the cache? My cypress job cache is currently storing 3 versions of Cypress (I only use 1) and is therefore taking up time to save/restore for no reason.

**Comment by mjhenkes** [comment]
`cypress cache prune`

**Comment by tsposato** [comment]
> `cypress cache prune`

Is it possible to do that via the GitHub action in some way?

**Comment by MikeMcC399** [comment]
Provided github-action is allowed to install Cypress and manage the cache itself then it will use a new cache if Cypress is updated.
