### ISSUE TITLE
Option to override ci-build-id

### ISSUE THREAD

**Issue by James-Quigley** [cypress-io/github-action#34]
Would be awesome for us to be able to override the ci-build-id. Right now when using either -record or -parallel, it is set for us as `${GITHUB_WORKFLOW} - ${GITHUB_SHA}`

**Comment by dominicroessner** [comment]
The code where this is set currently:

https://github.com/cypress-io/github-action/blob/master/index.js#L285

**Comment by bahmutov** [comment]
Done in https://github.com/cypress-io/github-action/pull/38

**Comment by blake-newman** [comment]
For those that may be interested: https://medium.com/attest-engineering/adding-a-unique-github-build-identifier-7aa2e83cadca

**Comment by bahmutov** [comment]
Nice @blake-newman !!! I will include this post in our readme for parallel runs https://github.com/cypress-io/github-action#parallel
