### ISSUE TITLE
Massive log output after v2.8.4

### ISSUE THREAD

**Issue by efeubiqube** [cypress-io/github-action#343]
After upgrading from v2.8.4. I am getting a massive logs on all runs which seems to be cause by how the cache is uncompressed. 

on v2.8.4

```

134 Received 729076687 of 729076687 (100.0%), 9.3 MBs/sec
135 Cache Size: ~695 MB (729076687 B)
136 /bin/tar -z -xf /home/runner/actions-runner/_work/_temp/c8b5a04f-39dc-4ec3-a291-359198871c8d/cache.tgz -P -C /home/runner/actions-runner/_work/my_project/my_project
137 ##[debug]npm cache hit yarn-linux-x64-
.....

```

2.9.0+

```

71 Received 34643528 of 34643528 (100.0%), 3.3 MBs/sec
72 /bin/tar -z -tf /home/runner/actions-runner/_work/_temp/c18677f0-4588-4bdd-a00a-445a5a0f987c/cache.tgz -P
73 ../../../../.cache/yarn/
74 ../../../../.cache/yarn/v6/

```

I don't understand why this `-C ...` part got remove or why this is happening now.

**Comment by bahmutov** [comment]
You mean the logs of every file downloaded and unzipped by the cache action?

**Comment by efeubiqube** [comment]
> You mean the logs of every file downloaded and unzipped by the cache action?

Something like that. Log gets so big that it affects the job itself. It makes very complicated to follow along the job watch the logs. 

the only difference I see is the `-C... ` part that seems to prevent that massive verbose.

**Comment by bahmutov** [comment]
Do you have the debugging on? https://github.com/cypress-io/github-action#debugging

Because that's what causing the massive logs from actions/cache I noticed https://github.com/actions/cache/issues/560

**Comment by efeubiqube** [comment]
No DEBUG was enable. Only thing that changed was the cypress-io/github-action from 2.8.4 to 2.9.7. 

Btw, I had to fix the version on 2.8.4 when `@v2` upgrade to. 2.9.0 because of this.

**Comment by bahmutov** [comment]
Weird. Can you figure out which commit or dependency version bump is causing the problem?

**Comment by efeubiqube** [comment]
> Weird. Can you figure out which commit or dependency version bump is causing the problem?

I see a huge refactor on the index.js. The line seems be `index.js@46200`,  but it seems to be only removing the `^M` character.

I see that the -C is there, but for some reason it's not happening on v2.9+

**Comment by dhadka** [comment]
Looks like https://github.com/actions/toolkit/pull/650 introduced this issue as it started printing the contents if debugging output is enabled.  

@efeubiqube Can you please double-check that the `ACTIONS_STEP_DEBUG` secret is not set on the affected repo?

**Comment by efeubiqube** [comment]
@dhadka yes, ACTIONS_STEP_DEBUG secret was set. I missed that this variable was on secret, I was only looking at the yml file. My bad.

I have removed that and it's working. Thanks
