### ISSUE TITLE
Error: Cannot find module 'vee-validate/dist/locale/en.json' in Cypress

### ISSUE THREAD

**Issue by MahmoudGhalayini** [cypress-io/github-action#349]
I'm implementing dynamic importing depend on my application's local. It's working fine in my development environment but in cypress I get this error in the console `Error: Cannot find module 'vee-validate/dist/locale/en.json.`

**Comment by bahmutov** [comment]
Please provide a reproducible example explaining the problem. Right now there does not seem to have enough information

**Comment by MahmoudGhalayini** [comment]
I'm using Cypress with Vue2. Earlier I was import my validation messages statically, it was loading fine in cypress 
`import { messages } from 'vee-validate/dist/locale/en.json';`. After importing the messages dynamically 

```
function setValidationLocalization(selectedLocaleCode) {
  import(`vee-validate/dist/locale/${selectedLocaleCode}.json`).then(locale => {
    localize(selectedLocaleCode, locale);
  });
}
```

My test started to fail and I this console error `Error: Cannot find module 'vee-validate/dist/locale/en.json.`

**Comment by bahmutov** [comment]
Can you create a repo with a reproducible example? Does it work locally?

**Comment by MahmoudGhalayini** [comment]
Yeah sure, It works fine the in development environment. Pardon me if any provided code isn't in cypress scope but for some reason the behavior after changing the way of the import.

**Comment by MahmoudGhalayini** [comment]
@bahmutov Here is a repo for the current problem https://github.com/MahmoudGhalayini/cypress-demo

**Comment by MahmoudGhalayini** [comment]
@bahmutov Hi, Did you check the issue with the repo please? Thanks

**Comment by bahmutov** [comment]
Seems like the problem with Cypress test runner itself, not with this github action. From the looks of it, I think this is because you are using a dynamic import that Cypress' bundler does not support.
