### ISSUE TITLE
No way to manually provide pull_request information?

### ISSUE THREAD

**Issue by dclowd9901** [cypress-io/github-action#350]
Hi,

In our setup, we use `workflow_dispatch` to manually kick off our cypress runs. Because of this, the workflow dispatches are run without a `pull_request` or `pull_request`-like context. Because of this (I believe), our dashboard does not contain any PR information related to test runs. Is there a way to manually provide PR information to the Cypress github action so that we can associate those runs with their appropriate PRs?

**Comment by bahmutov** [comment]
Great question, but running on `workflow_dispatch` ... does not have a pull request, right? So what would the PR info even be in this case?

**Comment by dclowd9901** [comment]
It’s true. We have a workaround that manually digs up the pull request via
api call. I was just hoping there was a way to manually provide that
information.

**Comment by bahmutov** [comment]
I don’t mind working on this, we had this question come up often enough

**Comment by dclowd9901** [comment]
That would be awesome! Thanks for all the great work!

**Comment by Sporradik** [comment]
We would also really appreciate this feature and I'm curious if there is any update on this.

We are trying to do something similar using `repository_dispatch`, where we can provide a payload to configure a pull request number.

We have a prototype working where we use `repository_dispatch` trigger adding a label to a PR and then the label trigger kicks off cypress. However, this intermediate label step is quite slow and it would be nice to trigger cypress directly in a way that passes our required PR checks.

**Comment by MikeMcC399** [comment]
- See https://github.com/cypress-io/github-action#automatic-pr-number--url-detection

**Comment by dclowd9901** [comment]
I’ve since moved to a position where we’re using Jenkins instead of GHA (groan), but thanks for moving this forward and out!
