### ISSUE TITLE
Question about containers

### ISSUE THREAD

**Issue by JamesSingleton** [cypress-io/github-action#359]
When running in parallel like the [example](https://github.com/cypress-io/github-action#parallel) given, are those containers docker containers? Or will Cypress only use docker containers if you specify something like `container: cypress/included:6.8.0`? Just curious if the action is spinning up docker images behind the scenes.

**Comment by bahmutov** [comment]
The Cypress GH Action does not spawn or create any additional containers - it only links the multiple containers spawned using the matrix strategy into a single logical Dashboard run and into splitting the specs amongst the machines. See the [Cypress parallelization](https://on.cypress.io/parallelization) guide for the explanation.
