### ISSUE TITLE
Improve Cypress Dashboard Support

### ISSUE THREAD

**Issue by prescottprue** [cypress-io/github-action#36]
There are a few things happening when using with Cypress Dashboard:

1. Commit message is not showing, instead a somewhat unclear of merge info is included even though no merge is going on (see picture below)
1. The branch name doesn't show at all (usually above the commit message)
1. The environment shows up as "Unknown". For Gitlab it shows "Gitlab #123" the number being the build number. Maybe for this it could be a link to the action run? (see picture below)
1. Quitting a Github Action run while it is running test leaves the run in the dashboard in the "running" state (as if the dashboard was never notified about the cancel)

![image](https://user-images.githubusercontent.com/2992224/69376356-2683c480-0c78-11ea-8bd3-26998963aba3.png)

Not sure if this is the right code base for the changes, but wanted to get it reported

**Comment by bahmutov** [comment]
Let's wait until https://github.com/cypress-io/cypress/pull/5687 is released in 3.7.0 it should fix 2 and 3. For 1 - this is pull request event right, so I am not sure what a beter name would be ;)

**Comment by prescottprue** [comment]
#4 is still an issue here - should I open a new issue for that?

**Comment by bahmutov** [comment]
@prescottprue not sure what you mean - #4 is MacOS caching? Maybe open a new issue with details

**Comment by prescottprue** [comment]
Item 4 in the above list is what I was referencing, but it picked up that as an issue
