### ISSUE TITLE
Videos are not loading on dashboard

### ISSUE THREAD

**Issue by Renato66** [cypress-io/github-action#361]
I got 2 actions [here](https://github.com/Renato66/chatfood/actions)

1st is [test-e2e.yml](https://github.com/Renato66/chatfood/blob/main/.github/workflows/e2e-test.yml) it uploads the video [dashboard run 14](https://dashboard.cypress.io/projects/fg718b/runs/14/specs)
2nd is [cypres.yml](https://github.com/Renato66/chatfood/blob/main/.github/workflows/cypress.yml), that uses cypress-io/github-action; doesn't upload the video [dashboard run 15](https://dashboard.cypress.io/projects/fg718b/runs/15/specs)

made it looking at an example [cypress-realworld-app](https://github.com/cypress-io/cypress-realworld-app/blob/develop/.github/workflows/main.yml), am I doing anything wrong?

**Comment by jennifer-shehane** [comment]
@Renato66 These runs are showing as being run in Cypress 3.8.3. Please try updating to the latest version as this version is very old to see if the issue persists because it may have been fixed.

**Comment by Renato66** [comment]
@jennifer-shehane thanks, it's working now :D
