### ISSUE TITLE
Save or Prevent recordings and screenshots in Github Action?

### ISSUE THREAD

**Issue by mesqueeb** [cypress-io/github-action#380]
I have set up a Github action that runs my tests.
It seems to also creates recordings and screenshots, on the ubuntu instance, but obviously I can't access them now.

I know it's possible to link to the Cypress console, but I was wondering two things:

1. Is there any way to commit the recordings to the same branch and delete them again if all tests pass?
2. Is there any way to just prevent screenshots and recordings to be made to make the tests complete faster?

**Comment by davidlinse** [comment]
regarding the 2nd point, have a look at the configuration options of the action to disable screenshots and videos.

regards
~david

**Comment by nagash77** [comment]
I am going to close this issue as it is quite old at this point.  If folks are seeing this behavior in current versions of Cypress please open a new ticket with a reproducible example and we will be happy to investigate.
