### ISSUE TITLE
Preview deployment example with dependency caching

### ISSUE THREAD

**Issue by kylemh** [cypress-io/github-action#385]
I've been following [this](https://glebbahmutov.com/blog/develop-preview-test/#github-checks) article, but I realized that we can't simply leverage https://github.com/actions/cache because you can't write to the cache during `deployment_status` events.

Unsure of any workarounds.

**Comment by mthines** [comment]
https://github.com/actions/cache/issues/598

**Comment by MikeMcC399** [comment]
I suggest to close this issue. It may still be relevant, however it is not a github-action bug, more of a "how-to" question.

**Comment by kylemh** [comment]
Since the discussions tab is unavailable... I could adjust this to be a feature request?

github actions seems entirely uninterested in adding caching to the specific lifecycle area of actions: https://github.com/actions/cache/issues/319

Without their action, is there anything the cypress github action can do to cache dependencies at any phase? Even if it's _only_ for paying customers and it's like remote cache uploading...

As it stands, I can't justify moving any of my projects to this much more logical and easier-to-write flow because it runs so much slower.

**Comment by MikeMcC399** [comment]
@kylemh 

I'm happy to mark this as an enhancement request. It needs investigation to check on the feasibility, as the action relies on     [@actions/cache](https://www.npmjs.com/package/@actions/cache) from the [GitHub Actions toolkit](https://github.com/actions/toolkit/tree/main/packages/cache) for its dependency caching capabilities.

**Comment by MikeMcC399** [comment]
@kylemh 

I took at look at the blog article [Test the Preview Vercel Deploys](https://glebbahmutov.com/blog/develop-preview-test/) that is based on a legacy version of Cypress and integrating with Vercel.

Does this issue still occur with current versions of Cypress and `github-action`? If yes, then logs would be helpful  in order to understand the issue better.

**Comment by MikeMcC399** [comment]
The blog post [Test the Preview Vercel Deploys](https://glebbahmutov.com/blog/develop-preview-test) dated Aug 20, 2020 does not mention the caching restrictions in the demonstrated legacy setup although the restrictions would also have applied at the time of publication.

Unfortunately this enhancement request for Vercel deployment appears to not be compatible with the GitHub Actions caching mechanism, which assigns caches to branches (see [Matching a Cache Key](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#matching-a-cache-key)).

If the GitHub Actions [deployment_status](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#deployment_status) event is triggered by Vercel without a `GITHUB_REF` (see [GitHub Default Environment Variable](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables)) then there is no branch reference available to work with a cache, so any cache actions fail.

- https://github.com/vercel/vercel/discussions/7581 discusses this topic.

I suggest to close this request as not being feasible. If there are changes made on the Vercel side, it could be re-opened.

**Comment by kylemh** [comment]
The changes I am seeking are irrelevant to Vercel. Vercel caching works well and automatically. I am interested in caching the dependencies related to the testing via the GitHub action.

Github seems uninterested in making the changes to allow for caching at the relevant life cycle point. I thought perhaps it could be an automatic aspect of this reusable action.

**Comment by kylemh** [comment]
Understood
