### ISSUE TITLE
different cypress package.json in e2e/

### ISSUE THREAD

**Issue by Sebastian-Haehnlein** [cypress-io/github-action#40]
hi,

our folder structure is slightly different. we outsourced cypress to e2e/

```
repo/
  app/
  e2e/
    cypress
    cypress.json
    package.json <- (e2e is a seperate package)
  package.json
```

is there a solution to handle this?

**Comment by bahmutov** [comment]
hmm, not right out of the box, no. Maybe by adding another parameter for a folder name to use while installing ...

**Comment by glambert** [comment]
Yes that would be great, we have a similar setup with a monorepo, where each app have their own `package.json` under `packages/*` 😄

**Comment by bahmutov** [comment]
see, the problem there is how would you cache and restore each package there, since that would require lots of logic. I am thinking more like - use https://github.com/bahmutov/npm-install (that would need to be extended to allow separate workind directory first) and then extend this package with working directory support like I said above

**Comment by bahmutov** [comment]
Update: I have implemented `working-directory` in `npm-install` https://github.com/bahmutov/npm-install/commit/f4bd98f449fe6710ccfa847d95d3bdf0684c3d7c and now need to think how to combine it with Cypress

**Comment by bahmutov** [comment]
I think release https://github.com/cypress-io/github-action/releases/tag/v1.17.0 should make it work (combined with https://github.com/bahmutov/npm-install action)

**Comment by glambert** [comment]
Great!

Now what if my app + e2e tests are within a sub-folder of a monorepo, for example:

```
root
  - packageA/
    - cypress/
    - src/
    - package.json
```

I want to install deps in `root/packageA/` and run tests from there as well (both my app deps and Cypress deps are there).

**Comment by bahmutov** [comment]
Sure, just do
```
- uses: cypress-io/github-action@v1
  with:
    working-directory: packageA
```
and it should all work. Note: you need either yarn.lock or package-lock.json
