### ISSUE TITLE
Skipping Chromium download when using Percy

### ISSUE THREAD

**Issue by alexbjorlig** [cypress-io/github-action#411]
According to percy docs [here](https://docs.percy.io/docs/skipping-puppeteer-chromium-download), it should be possible to avoid having percy download chromium, by setting an env varible with the path to a chrome browser;

```
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD - Set this to true
PUPPETEER_EXECUTABLE_PATH - Set this to the path of the Chrome browser on your system / CI image.
```

Did anyone have luck with this - I'm unsure what the path for `PUPPETEER_EXECUTABLE_PATH` should be.

**Comment by alexbjorlig** [comment]
After some trial and error, I now avoid re-downloading chromium by setting this env variable:

```
PERCY_BROWSER_EXECUTABLE: /usr/bin/chromium-browser
```

**Comment by ngraf** [comment]
For what purpose Percy needs chromium?
I assumed Percy renders the screenshots in the cloud based on the DOM the test sends over to Percy? Or did I got it wrong here?

**Comment by MikeMcC399** [comment]
@ngraf 

I guess you need to be researching more on the https://docs.percy.io/ site since this closed issue was about Percy and PUPPETEER.

**Comment by ngraf** [comment]
Yes, the question is more directed to Percy community, not Cypress community.

**Comment by MikeMcC399** [comment]
@ngraf 
https://github.com/puppeteer/puppeteer#default-runtime-settings
"By default, Puppeteer downloads and uses a specific version of Chromium so its API is guaranteed to work out of the box."

**Comment by ngraf** [comment]
I understand. Seems like for stability reasons they use their own browser to prepare their payload which includes DOM and asset informations. At least with PERCY_BROWSER_EXECUTABLE: /usr/bin/chromium-browser they provide some flexibility.
