### ISSUE TITLE
Is it possible to run against chrome-beta?

### ISSUE THREAD

**Issue by alexbjorlig** [cypress-io/github-action#412]
The objective would be to detect breaking changes in futures versions of Chrome?

**Comment by sergiubcn** [comment]
I haven't tried this myself to be honest, but by looking at the code it should work, because it basically pushes the value provided for the `browser` key in the `yml` config file:
```
 if (browser) {
    cmd.push('--browser')
    // TODO should browser be quoted?
    // If it is a path, it might have spaces
    cmd.push(browser)
  }
```
As long as the binary is present in the CI agent environment a path to that could be provided.

**Comment by MikeMcC399** [comment]
@alexbjorlig 

The answer to your question 

> Is it possible to run against chrome-beta?

is "yes". See Cypress documentation: [Browsers](https://docs.cypress.io/guides/guides/launching-browsers#Browsers). 

It is however your responsibility to install Google Chrome beta as the [standard GitHub runner images](https://github.com/actions/runner-images) only include a recent Google Chrome stable version as default.
