### ISSUE TITLE
Add comment only on failed tests

### ISSUE THREAD

**Issue by alexcroox** [cypress-io/github-action#420]
When someone creates a PR I will get a second email with the Cypress summary comment which gets very spammy with lots of activity. I wondered if there was a way to configure only adding a PR summary comment if any of the tests fail?

![image](https://user-images.githubusercontent.com/1065835/133246588-85ad2404-a980-44c8-abd9-1fda174f6459.png)

**Comment by MikeMcC399** [comment]
This issue refers to the [GitHub Integration](https://docs.cypress.io/guides/cloud/integrations/source-control/github) not to `cypress-io/github-action` so it can't be solved by the action.
