### ISSUE TITLE
Add Publisher Verification for cypress-io

### ISSUE THREAD

**Issue by atsai1220** [cypress-io/github-action#426]
Cypress is amazing and vouched for by developers around the world! What are the odds of getting this organization verified by GitHub? Is there anything we can help with?

https://docs.github.com/en/developers/github-marketplace/github-marketplace-overview/applying-for-publisher-verification-for-your-organization

**Comment by ktn1234** [comment]
Totally agree with @atsai1220! Would love to see cypress be officially verified by GitHub as well. Best E2E testing framework I've experienced 🥳

**Comment by MikeMcC399** [comment]
Is this what you were looking for?

![image](https://github.com/cypress-io/github-action/assets/66998419/72961810-ef2b-4f16-9aec-aefaf86e7d01)

**Comment by MikeMcC399** [comment]
Closing on the assumption that the request has been satisfied.
