### ISSUE TITLE
Running workflow with `headless=false` no longer opens headless chrome browser

### ISSUE THREAD

**Issue by alexcampbell86** [cypress-io/github-action#432]
Version: cypress-io/github-action@v2
Cypress version: 8.5

I'm running the workflow (latest version) with the parameter `headless=false`
![image](https://user-images.githubusercontent.com/54784541/135402446-4ee9c427-69c7-4704-ab13-f3f9fe71e454.png)

But when the browser launches, it is actually in headless mode:
![image](https://user-images.githubusercontent.com/54784541/135402506-2dde8830-bf56-4d63-95f3-8cbaf7fa65ea.png)

**Comment by sergiubcn** [comment]
Folks following this thread can maybe upvote my PR so we can get it merged sooner https://github.com/cypress-io/github-action/pull/409

**Comment by nagash77** [comment]
I am going to close this issue as it is quite old at this point.  If folks are seeing this behavior in current versions of github-action please open a new ticket with a reproducible example and we will be happy to investigate.
