### ISSUE TITLE
Using github actions, gives CI: Unknown in dashboard

### ISSUE THREAD

**Issue by dauledk** [cypress-io/github-action#44]
![Screenshot 2019-11-25 at 22 04 26](https://user-images.githubusercontent.com/9967422/69577886-a2ab3e80-0fcf-11ea-891f-7c8e9d8be2ef.png)

**Comment by jennifer-shehane** [comment]
There is a PR in our main product to collect this information that will be released as part of Cypress 3.7.0. This and other Git information should show in the Dashboard after that release. Closing since this is pending release in that repo. https://github.com/cypress-io/cypress/pull/5687
