### ISSUE TITLE
Request: Option to ignore dependencies apart from Cypress

### ISSUE THREAD

**Issue by ritwikvd** [cypress-io/github-action#469]
We're using the `deployment_status` event to trigger our e2e suite and since we test on our preview deployment, we have no need of installing dependencies apart from Cypress. This step currently takes around a minute to complete before tests run.

Currently, this action provides an install flag which we can set to false, and manually install Cypress ourselves after repo checkout, however, this results in a fresh install. 

I can see that this action internally checks for the global cache with a key based on the Cypress version found in the manifest, but this is not exposed as a configuration option.

We cannot use actions/cache since it requires the branch ref which is not provided with `deployment_status`.

If there's any workaround or if I've missed some config option, please let me know!

**Comment by MikeMcC399** [comment]
@ritwikvd 

This is an old request, so I guess it may not be relevant anymore. You might be able to point github-action to a directory with a lockfile which only contains Cypress in order to satisfy your parameters.

**Comment by MikeMcC399** [comment]
- This is related to https://github.com/cypress-io/github-action/issues/385

**Comment by MikeMcC399** [comment]
- Unfortunately, and for the same reasons discussed in #385, there is no solution in `cypress-io/gihub-action`, and this request is not feasible.
