### ISSUE TITLE
How can we implement https://github.com/bahmutov/cypress-repeat with this github action?

### ISSUE THREAD

**Issue by kpturner** [cypress-io/github-action#477]
It would be nice to be able to use the functionality provided with https://github.com/bahmutov/cypress-repeat with this github action. As far as I can see we would have to not use this action if we want to make use of the retry/rerun options in this plug-in.

**Comment by MikeMcC399** [comment]
@kpturner 

It does not look like the npm module [cypress-repeat](https://www.npmjs.com/package/cypress-repeat) is compatible with `cypress-io/github-action` usage.

I noticed in another post that you said you're not using github-action anymore, so your question is presumably stale for you.

**Comment by MikeMcC399** [comment]
@kpturner 

Sorry for disturbing you 🙂 ! I'm just trying to clean up the list of open issues, so I'll go ahead and close this one.
