### ISSUE TITLE
Dashboard state not updating

### ISSUE THREAD

**Issue by prescottprue** [cypress-io/github-action#48]
In the following cases the dashboard remains in the "running" state (as if it was never notified):
* If a test fails the action run fails
* As mentioned in #36 - Quitting a Github Action run while it is running

This results in test runs being indicated as taking 2+ hours within the dashboard even when the Github Action itself is done in less than 10 minutes (it shuts off due to the cypress command shutting down due to the failed test)

**Comment by bahmutov** [comment]
I am not sure I understand the situation - do you have public action to show this? The test fails, but the Cypress does not post completion to the Dashboard? Or does the Cypress Test Runner crash and leaves the job hanging?

**Comment by prescottprue** [comment]
I don't have a public action for this yet, but will work on making one. More the first - Cypress does not post completion in the failure case

**Comment by prescottprue** [comment]
Just found that there is an option in Github Actions [called fail-fast](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast) which controls builds in the matrix failing if another build in the matrix fails - I have found that setting this to false  (i.e. `fail-fast: false`) fixes the first bullet above (i.e. if a test fails the dashboard does not continue indicating running since the rest of the tests run).

@bahmutov We may want to add that to the README as the default setup since I don't believe that it would be common to want all matrix builds to fail in the case of one failing (which happens from a test failure). As mentioned, this prevents the dashboard from hanging in the "in progress" state

**Comment by jamime** [comment]
@bahmutov @prescottprue

The `fail-fast` approach is causing an issue for me.

I have a project that uses 20 runners (our maximum concurrency). When we receive a pr from a fork it won't receive the cypress dashboard secret token so it will be limited to 1 runner but the remaining 19 runners remain occupied. Our suite takes ~3 hours with one runner.

I tried to change the matrix size if the PR was raised from a fork, but it does not seem possible.

Is there another way that we could resolve the dashboard hanging instead of using `fail-fast`?

**Comment by dgreene1** [comment]
Should this issue still be referenced in the readme if the issue is truly solved and closed?

**Comment by h2oearth** [comment]
It seems like the `fail-fast:false` is here to stay in favour of https://www.cypress.io/blog/2023/02/15/cypress-cloud-auto-cancellation-is-now-available-via-cli. It would be nice if the customers under the Team plan could have these features for free!
