### ISSUE TITLE
Caching not available on GitHub Enterprise

### ISSUE THREAD

**Issue by wsams** [cypress-io/github-action#513]
Hello, I am looking to run Cypress tests within GitHub Actions, but having trouble due to the action trying to use caching. GitHub Enterprise does not yet have caching support like github.com - at least as far as I'm aware. This is what I see in the logs,

```
Saving NPM cache error: Unable to reserve cache with key npm-linux-x64-2357f551dce11df77e14a37071ec71d0bdf8256d8ca499fe6b748ad5e23eee3ac0d117cddd6f056417169ff5f0ab194ad00ef7a754ea993cc1a08a8d4de005a0, another job may be creating this cache.
Saving Cypress cache error: Unable to reserve cache with key cypress-linux-x64-2357f551dce11df77e14a37071ec71d0bdf8256d8ca499fe6b748ad5e23eee3ac0d117cddd6f056417169ff5f0ab194ad00ef7a754ea993cc1a08a8d4de005a0, another job may be creating this cache.
```

Is there any way to disable caching, or could support be added?

Thanks,
Weldon

**Comment by amitabhpandaa** [comment]
Hello,

Did you find any solution to the problem, even I face the same issue as given below,

/opt/hostedtoolcache/node/14.19.2/x64/bin/npx cypress verify

[STARTED] Task without title.
[SUCCESS] Task without title.
Saving NPM cache error: Unable to reserve cache with key npm-linux-x64-4a6c6fc5c44b866ced8c46034c0130244a7124faa06d238d9923c45049[56]
check_suite_focus=true#step:6:57)a5230c76dda314cd2831966a07dc7b6e[60]check_suite_focus=true#step:6:61)cacdb42561674e47c0765bbe8e4a2f88f3, another job may be creating this cache.
Saving Cypress cache error: Unable to reserve cache with key cypress-linux-x64-4a6c6fc5c44b866ced8c46034c0130244a7124faa06d238d9923c4504956a5230c76dda314cd2831966a07dc7b6e60cacdb42561674e47c0765bbe8e4a2f88f3, another job may be creating this cache.
Error: Not Found

Regards,
Amitabh

**Comment by ludwighogstrom** [comment]
Same here. Any updates?

**Comment by pauldambra** [comment]
Me three...

E.g. https://github.com/PostHog/posthog/runs/7151150940?check_suite_focus=true

**Comment by dzzk** [comment]
The same:

`Saving Cypress cache error: Unable to reserve cache with key cypress-linux-x64-15c5ba12d0b61fc47cf969b2bdd88312defa6e69d27875579c4d36e427f84bdc2600db432a458b919867a37c04b0777e85762eeb09f79e212ed18d70c5dec5b8, another job may be creating this cache.`

**Comment by adiqa** [comment]
Do we have any clue why is this happening?

**Comment by MikeMcC399** [comment]
[cypress-io/github-action](https://github.com/cypress-io/github-action) [v5.0.2](https://github.com/cypress-io/github-action/releases/tag/v5.0.2) uses ["@actions/cache": "3.0.6"](https://github.com/actions/cache/releases/tag/v3.0.6).

[@actions/cache v3.0.9](https://github.com/actions/cache/releases/tag/v3.0.9) added "Enhanced the warning message for cache unavailability in case of GHES."

Perhaps [cypress-io/github-action](https://github.com/cypress-io/github-action) could be  updated to use [@actions/cache v3.2.2](https://github.com/actions/cache/releases/tag/v3.2.2) to at least take advantage of a better warning message?

There is a long discussion in https://github.com/actions/cache/issues/505 about this and the [release notes for GHES 3.5.0](https://docs.github.com/en/enterprise-server@3.5/admin/release-notes#3.5.0) from May 31, 2022 state "Cache support for GitHub Actions on GitHub Enterprise Server is now generally available".

I don't personally have access to GitHub Enterprise, but perhaps the above research may throw some light on the problem?

Which version of GitHub Enterprise are people have problems with? GitHub Enterprise Cloud or GitHub Enterprise Server? If GitHub Enterprise Server, the [supported releases](https://docs.github.com/en/enterprise-server@3.7/admin/all-releases#currently-supported-releases) are currently 3.3 to 3.7.

**Comment by MikeMcC399** [comment]
@adiqa 

> Do we have any clue why is this happening?

See https://github.com/cypress-io/github-action/issues/513#issuecomment-1368080092

Could you say which version of GitHub Enterprise you are using?

**Comment by MikeMcC399** [comment]
- [cypress-io/github-action@v5](https://github.com/cypress-io/github-action/) was updated in [v5.0.5](https://github.com/cypress-io/github-action/releases/tag/v5.0.5) through PR https://github.com/cypress-io/github-action/pull/716 to use `"@actions/cache": "3.1.2"` from https://github.com/actions/cache.
- Are there still cache issues on GitHub Enterprise when using the latest v5 version of [cypress-io/github-action](https://github.com/cypress-io/github-action/)?

**Comment by MikeMcC399** [comment]
@wsams 

Do you still have questions or an open issue surrounding this topic? If not, perhaps you would like to close the issue, since nobody else has contributed with any further details.

**Comment by merrcury** [comment]
@MikeMcC399 I am facing this issue while running cypress on Github Enterprise Cloud.

**Comment by MikeMcC399** [comment]
@merrcury 

I don't believe that this issue is specific to GitHub Enterprise Cloud as I have seen it occurring on regular GitHub-hosted runners. Does the error clear if you wait for 24 hours?

Since the original title of this issue is "Caching not available on GitHub Enterprise" and this is no longer true, I would suggest closing this issue and starting a new one.

**Comment by merrcury** [comment]
Make sense @MikeMcC399. Let me dig more deeper. Thanks, I am not original author, can't close this.

**Comment by nagash77** [comment]
I am going to close this issue at this time.
