### ISSUE TITLE
`npm_package` variables not set when processing `cypress/plugins/index.js`

### ISSUE THREAD

**Issue by max-nextcloud** [cypress-io/github-action#524]
We're using a [webpack config](https://github.com/nextcloud/webpack-vue-config/blob/master/webpack.config.js#L30) that makes use of `npm_package_name` and `npm_package_version`.

These are not set during the [run](https://github.com/nextcloud/text/runs/5658398537?check_suite_focus=true#step:11:58) - which is confusing as it looks like `npx` is used to run the job.

I'd expect the `npm_package_...` variables to be set just like when i run `npx cypress run` locally.

**Comment by max-nextcloud** [comment]
[Setting](https://github.com/nextcloud/text/commit/3fa26b0702c538cab11325c9a78f499cd18913b6) the variable in env [fixes](https://github.com/nextcloud/text/runs/5659111283?check_suite_focus=true) the failing test.

**Comment by skjnldsv** [comment]
Ahaha, I see we had the same issue @max-nextcloud :cry:

**Comment by MikeMcC399** [comment]
Closing, since this is a stale, inactive issue.

**Comment by max-nextcloud** [comment]
> It looks like you were able to resolve your issue.

I was able to find a workaround by setting `npm_package_name` in the env even though it should be set by npx. If i remove the workaround the run still fails: https://github.com/nextcloud/text/actions/runs/6812145616/job/18524231320

> Can this be closed now?

Your choice. The issue in the action still is there but a workaround exists.
