### ISSUE TITLE
Cypress get long time after run on CI

### ISSUE THREAD

**Issue by golfzaptw** [cypress-io/github-action#53]
I have 2 file test and script below
```js
// API
describe('Group of test', function() {
  it('api test', function() {
    cy.getTodos()
  })
})
```
```js
// frontend
describe('Group of test', function() {
  before(function() {
    cy.log('run me on 1 time at all test start')
  })
  after(function() {
    cy.log('run me on 1 time at all test end')
  })
  beforeEach(function() {
    cy.log('run me always time at it is run')
  })
  afterEach(function() {
    cy.log('run me always time at it is run end')
  })
  context('Sub group of test', function() {
    it('test case 1', function() {
      cy.visit('/')
    })
    it('test case 2', function() {
      cy.visit('/')
    })
  })
})
```
The first file is passed but the second file isn't run. Can you help me ?
Can see my repo at [repo](https://github.com/golfzaptw/test-action)

**Comment by jennifer-shehane** [comment]
This repo is only for issues relating to Cypress GitHub actions. If you want to open an issue on our main project, you can open it [here](https://github.com/cypress-io/cypress/issues/new) with a completely reproducible example. This issue will be closed in this repository.

Also, check out our [community chat](https://gitter.im/cypress-io/cypress), it can be helpful for debugging issues or just answering questions you have about Cypress.

**Comment by golfzaptw** [comment]
@jennifer-shehane Yes, this issue relating to Cypress Github Action. You can see my action in here [Github action](https://github.com/golfzaptw/test-action/commit/521dad8182775d6cca57452d530b53883e85433f/checks?check_suite_id=376457362)
