### ISSUE TITLE
Keeps adding erroneous annotations even for successful runs

### ISSUE THREAD

**Issue by kpturner** [cypress-io/github-action#532]
We have a scheduled workflow that runs cypress tests (twice).  The tests are successful and the workflows complete successfully, but the github action stills adds erroneous/confusing annotations to the run:

![image](https://user-images.githubusercontent.com/308646/161936999-e787ec72-ba87-41b6-91c5-c374397157da.png)

What do these annotations mean and where do they come from?

**Comment by MikeMcC399** [comment]
Again, this is a stale issue, which unfortunately was not followed up at the time.
