### ISSUE TITLE
Dashboard records tests with the wrong commit message

### ISSUE THREAD

**Issue by kpturner** [cypress-io/github-action#533]
Imagine a scenario where you keep all your cypress tests on repo A and you have your application in repo B

In repo B you create a workflow that runs the cypress tests on PRs opened in repo B

The workflows checks out the code from the PR branch, and then has to check out the cypress tests into a subfolder.

The workflow then runs the cypress tests for the PR using this gitgub action, specify a working directory of the subfolder containing the cypress tests.

The test results are recorded in the Cypress Dashboard but are associated with the last commit message of the repo A rather than the commit message of repo B that triggered the tests to run.

This makes the dashboard very confusing, if not, impossible to work with in a meaningful way.  Every test run is associated with the same incorrect commit message.

How does one rectify this?

**Comment by conversaShawn** [comment]
Resolved by checking [GitHub settings](https://github.com/settings/profile) to confirm you have given Cypress the correct access?

![image](https://user-images.githubusercontent.com/48733734/164103624-b6362d60-3a77-4651-8f77-d86d4469d478.png)

**Comment by kpturner** [comment]
I don’t think that helps really.  There are two repos and Cypress needs access to both: one with the tests defined (that runs them in its own set of workflows) and one that runs the tests by checking out the first repo and running the tests against its own latest committed change.  It is the latter that has the issue, because cypress registers the results with the last commit message from the repo holding the tests, not the repo whose commit/push triggered them.  The only way I could get around it was to delete the .git folder in the repo holding the tests before actually running them.  From: Shawn Harris ***@***.***>Date: Tuesday, 19 April 2022 at 22:20To: cypress-io/github-action ***@***.***>Cc: Kevin Turner ***@***.***>, Author ***@***.***>Subject: Re: [cypress-io/github-action] Dashboard records tests with the wrong commit message (Issue #533)Resolved by checking GitHub settings to confirm you have given Cypress the correct access?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by MikeMcC399** [comment]
Closing, since this issue is stale and the submitter wrote that they are no longer using the action.
