### ISSUE TITLE
Provide Docker image with Node 12.14.

### ISSUE THREAD

**Issue by olegburov** [cypress-io/github-action#54]
Could you please build and push Docker image with Node 12.14?

**Comment by bahmutov** [comment]
Sure, open an issue in cypress-Docker-images please

**Comment by jennifer-shehane** [comment]
Closing as this is concerned with https://github.com/cypress-io/cypress-docker-images repo.

**Comment by olegburov** [comment]
Sorry, I didn't see the other repo. Open a couple PRs https://github.com/cypress-io/cypress-docker-images/pull/194 and https://github.com/cypress-io/cypress-docker-images/pull/195.
