### ISSUE TITLE
testFiles order ignored when recording

### ISSUE THREAD

**Issue by nielsuit227** [cypress-io/github-action#545]
I use the `cypress.json` settings to specify the order of tests (necessary for E2E signup testing). 
This works nicely, until I set the Github action `record` setting to true. Afterwards, it runs in alphabetical order.

**Comment by admah** [comment]
This is a long-standing Cypress issue as [outlined here](https://github.com/cypress-io/cypress/issues/390), and not caused by an issue with this repo.
