### ISSUE TITLE
wait-on doesn't support Basic Auth

### ISSUE THREAD

**Issue by miiimooo** [cypress-io/github-action#546]
I have a staging environment with Basic Auth enabled

waiting on "https://XXXXX/" with timeout of 120 seconds
https://XXXXXX/ timed out on retry 6 of 5, elapsed 150930ms, limit 150000ms
Error: Response code 401 (Unauthorized)

**Comment by miiimooo** [comment]
Thanks that works it seems

**Comment by philwolstenholme** [comment]
You can also send a `Authorization` header where the value is `Basic: ` then your credentials in the format `username:password` but encoded as base64
