### ISSUE TITLE
spec argument not being escaped with quotes

### ISSUE THREAD

**Issue by corydeppen** [cypress-io/github-action#551]
We've run into an issue where Cypress tests are stalling in CI and it seems like it may be related to the `--spec` arg that's not being properly escaped with quotes. This is being run using `cypress-io/github-action@v2.10.1` on the `cypress/browsers:node14.17.6-chrome100-ff98` image.

```bash
with:
  browser: chrome
  headless: true
  working-directory: packages/app
  spec: cypress/integration/mocked/account/**/*.ts
  config: chromeWebSecurity=false,video=false
  command-prefix: --
  record: false
  config-file: cypress.json

Cypress test command: npx -- cypress run --headless --config chromeWebSecurity=false,video=false --spec cypress/integration/mocked/account/**/*.ts --config-file cypress.json --browser chrome
/usr/local/bin/npx -- cypress run --headless --config chromeWebSecurity=false,video=false --spec cypress/integration/mocked/account/**/*.ts --config-file cypress.json --browser chrome

Cypress:        9.6.0
Browser:        Chrome 100 (headless)
Node Version:   v14.17.6 (/usr/local/bin/node)
```

I was expecting the command to look like `--spec "cypress/integration/mocked/account/**/*.ts"`. The reason I believe the stalling test may be related to this is because I can reproduce the issue locally and when I escape the spec arg with quotes the tests all run without one stalling. The `quoteArgument` function that's [used in the action source](https://github.com/cypress-io/github-action/blob/master/index.js#L540) appears to only add/fix quotes on Windows.

I appreciate any thoughts in helping us get past this stalled test issue.

**Comment by MikeMcC399** [comment]
@corydeppen 

You didn't get any response to your issue submission from more than a year and a half ago. In the meantime the version of Cypress specified in the issue has moved to legacy status.

Is there still a need to look at this? If not, then I would close the issue.

**Comment by MikeMcC399** [comment]
Closing, since there was no further feedback.
