### ISSUE TITLE
Custom auth0 login command fails in CI

### ISSUE THREAD

**Issue by bunge12** [cypress-io/github-action#554]
With the new release of v9.6.0 and the new `cy.session` and `cy.origin`, along with multiple guides ([guide 1](https://community.auth0.com/t/end-to-end-testing-with-cypress-and-auth0/19082/111), [guide 2](https://cypress.io/blog/2022/04/25/cypress-9-6-0-easily-test-multi-domain-workflows-with-cy-origin/)), I tried updating our Cypress tests to run using the new functionality. While **I was able to run the commands locally**, they would always fail on GitHub Actions. From the videos and screenshots, it looks like whenever the login command would run and redirect to auth0, the app would crash. I thought the issue might be with the app itself, but the **tests ran successfully on Circle CI**. 

Stack used:

- Cypress 9.7.0
- Node v14
- Chrome (headed)
- Ubuntu-20

The command in question:
```javascript
Cypress.Commands.add('loginAsUser', (email, password) => {
	const args = { email, password };
	cy.session(args, () => {
		// visit homepage
		cy.visit('/');
		cy.get('button[data-cy=login]').click();
		// redirects to Auth0
		cy.origin('AUTH0_DOMAIN', { args }, (args) => {
			cy.get('#username').type(args.email);
			cy.get('#password').type(args.password);
			cy.get('button')
				.contains(/^Continue$/)
				.click();
		});
		// assert we've returned to the site
		cy.get('h6[data-testid=clock]').should('exist');
		cy.get('button[data-cy=logout-button]').should('exist');
	});
});
```

The output on Github Actions:
```
The command was expected to run against origin https://auth0.com but the application is at origin `chrome-error://chromewebdata`.

This commonly happens when you have either not navigated to the expected origin or have navigated away unexpectedly.

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Login Behaviour`
      at Object.eval [as setup] (http://localhost:5000/__cypress/tests?p=cypress/support/index.js:38433:8)
```

**Comment by Artem-Bosenko-01** [comment]
Hi @bunge12, have you solved this issue? If yes, could you please share the solution?

**Comment by bunge12** [comment]
Hi @Artem-Bosenko-01, we opted to run Cypress on CircleCI and it runs without any issues using the command from above.

**Comment by MikeMcC399** [comment]
Closing, since a workaround was found.
