### ISSUE TITLE
parallel-group-params-mismatch caused by osVersion

### ISSUE THREAD

**Issue by johnpolacek** [cypress-io/github-action#558]
Similar to #7199 we are running into an issue where we hit the `parallel-group-params-mismatch` error, in this case due to a mismatch in `osVersion`. This happens when Github Actions rolls out an update - see https://github.com/actions/virtual-environments/issues/2505#issuecomment-764001469

Is there anything that can be done to avoid this?

**Comment by Minjor** [comment]
same problem here

**Comment by MaximeHeckel** [comment]
Same here!

**Comment by aangelinsf** [comment]
Would love to know how to get around this.

**Comment by MikeMcC399** [comment]
The workaround was added to the documentation https://github.com/cypress-io/github-action#parallel some time ago:

> During staged rollout of a new GitHub-hosted runner version, GitHub may provide a mixture of current and new image versions used by the container matrix. It is recommended to use a [Docker image](#docker-image) in the parallel job run which avoids any Cypress Cloud errors due to browser major version mismatch from the two different image versions. A [Docker image](#docker-image) is not necessary if testing against the default built-in Electron browser because this browser version is fixed by the Cypress version in use and it is unaffected by any GitHub runner image rollout.
