### ISSUE TITLE
Can we please have a beautiful  summary 🥺? 

### ISSUE THREAD

**Issue by lessless** [cypress-io/github-action#559]
Hi,

Recently GitHub released job summaries https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/

And it seems that they were built exactly for Cypress :D . For example, to provide overall test execution stats: total number of tests,  number of tests passed, number of tests failed, and time to run the suite.

**Comment by jdwillemse** [comment]
I'm using cypress-io/github-action@v4 on pull_request event but do not see a summary when the workflow completes. Is there some specific setup required to see the summary?

**Comment by cmotsn** [comment]
Do note that when using a custom test command, eg.
```
  - uses: cypress-io/github-action@v5
    with:
      command: npm run e2e:ci
```

_then the summary will not be generated_, because the custom command  'by-passes a lot of the functions of cypress/github-action' , as mentioned on #882.
