### ISSUE TITLE
Wrong official information

### ISSUE THREAD

**Issue by Nicolopez603** [cypress-io/github-action#563]
On the official documentation page, they are using an old version (v2) when the one normally used is v4.

Official example: - uses: cypress-io/github-action@v2

Example that should be: - uses: cypress-io/github-action@v4

**Comment by h2oearth** [comment]
<img width="1180" alt="Screen Shot 2022-06-06 at 2 25 46 pm" src="https://user-images.githubusercontent.com/97860372/172094819-0e08f976-7499-457a-826a-6757ac5cdefc.png">

**Comment by Nicolopez603** [comment]
![image](https://user-images.githubusercontent.com/81532585/172205668-c7e5a4bc-4c3b-42e1-ac0c-46420151ad24.png)

**Comment by admah** [comment]
@Nicolopez603 thanks for pointing this out. I've updated the version in [this PR.](https://github.com/cypress-io/cypress-documentation/pull/4553)

**Comment by Nicolopez603** [comment]
Awesome! Thank you @admah
