### ISSUE TITLE
Can we output the type of the tests?

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/github-action#571]
https://github.com/cypress-io/github-action/blob/be2de7b1fe1cdafb4a3c8da0a3746476ef636b65/index.js#L77

Because right now running E2E and then component tests creates kind of confusing output

![Screen Shot 2022-06-17 at 14 58 14](https://user-images.githubusercontent.com/2212006/174386220-98ec55e7-3a62-481a-8540-fa0c0ede17ae.png)
7

One could also include a link to the docs explaining the test statuses https://on.cypress.io/writing-and-organizing-tests#Test-statuses because it is not that trivial (Skipped is not `it.skip`)

**Comment by MikeMcC399** [comment]
- This issue is resolved in [v6.6.0](https://github.com/cypress-io/github-action/releases/tag/v6.6.0) through PR https://github.com/cypress-io/github-action/pull/1056.
