### ISSUE TITLE
Flaky tests that pass during retries mark PR as failed

### ISSUE THREAD

**Issue by reintroducing** [cypress-io/github-action#581]
I have retries set up and for whatever reason a test or two usually is flaky when run in CI. With 2 retries enabled, the test usually passes on one of the retries but is marked as flaky, which is fine. What isn't fine is that the PR shows the following:
<img width="497" alt="Screen Shot 2022-07-06 at 9 22 37 AM" src="https://user-images.githubusercontent.com/259901/177597911-4e2d3ae9-ae9b-4181-97d7-5c433cf196de.png">
which in turn marks the whole PR as failed:
<img width="244" alt="Screen Shot 2022-07-06 at 9 23 29 AM" src="https://user-images.githubusercontent.com/259901/177598065-de47b8e7-549f-4662-ba9e-a732fd730227.png">
I understand that a flaky test may or may not fail here and there, but it shouldn't mark the whole thing as failed, because the test is flaky and technically passing. For what its worth, that same test is not flaky when run in local through the Cypress app, but all things considered, it DID pass in CI after a retry so it shouldn't be showing up as a failed run for flakyness unless all retries also failed. 

what's even more confusing is that in Cypress dashboard, the run shows up as passed (as it should).
<img width="664" alt="Screen Shot 2022-07-06 at 9 26 20 AM" src="https://user-images.githubusercontent.com/259901/177598524-44117e15-272d-41db-b2e8-69b9ace64d85.png">
the last run with the green circle and white check of this screenshot is the same run as the PR screenshots from up above.

This tends to be confusing because if Cypress dashboard marks the run as passed, so should the PR, no?

**Comment by conversaShawn** [comment]
@reintroducing  The expected behavior is any reports of flake will result in a failed GitHub status check.
 
Here are a couple of options to prevent this:

- Turn off the `Report flaky tests` option in the Project settings in the Cypress Dashboard

- Remove the GitHub check for `cypress/flake` that is currently marked as required to not required

**Comment by reintroducing** [comment]
@conversaShawn I can confirm that turning off the `Report flaky tests` option "fixed" this, thank you.

**Comment by igarashitm** [comment]
It would be nice if I can configure this in GitHub Action parameter. Even if it's not required, all the pull requests will get the failure icon in the PR list. This makes it harder to find which PR is actually failing.
