### ISSUE TITLE
Cypress 9.5.3 error since chrome_security=false is not working as intended

### ISSUE THREAD

**Issue by narayananpalani** [cypress-io/github-action#584]
Previously, cypress v8.5 worked with axe-devtools binaries and we manage to extract the axe devtools report for accessibility scan. But after upgrading to cypress version 9.5.3, axe-devtools based test throwing error on iframe:
![image](https://user-images.githubusercontent.com/14081024/180484004-7c1caa14-b192-47c0-8097-1e20c903cf5b.png)

Note: axe-devtools working with chrome_security=false in first page of the test but the second page in which chrome_security=false is not working as intended and throwing cross-reference error of iframe due to cypress security policy. please would you fix it?

**Comment by MikeMcC399** [comment]
@narayananpalani 

This is not a problem which can be solved by github-action.

If you are still experiencing this issue, please report it in https://github.com/cypress-io/cypress/issues instead.
