### ISSUE TITLE
[Feature request] Add support for Bun

### ISSUE THREAD

**Issue by Kocal** [cypress-io/github-action#585]
Just opening a feature request for [Bun](https://github.com/oven-sh/bun) support. It implies:
- support for install deps command
- support for deps caching 

I may open a new PR soon, if I find that Bun really improves performances on our project.

**Comment by h2oearth** [comment]
Any updates Bun 1.0 (prod ready) is out, this is a must nowadays

**Comment by lundjrl** [comment]
Any updates here?

**Comment by MikeMcC399** [comment]
If somebody wants to use Bun with GitHub Actions, they can use the workflow [.github/workflows/single.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.github/workflows/single.yml) from the demo repo [cypress-io/cypress-example-kitchensink](https://github.com/cypress-io/cypress-example-kitchensink/) as a template (which does not rely on `cypress-io/github-action`).

1. Replace `actions/setup-node@v3` by `npm install -g bun`
2. Change the cache lockfile from `package-lock.json` to `bun.lockb`
3. Add a new cache for `~/.bun`
4. Replace `npx` calls with `bun` calls

`bun install cypress` does not run the postinstall script, so you would also need to run `bun cypress install` manually.

I haven't seen any feedback from the Cypress team how they see Bun and I don't see any official support from Cypress for Bun either, so I would be cautious about using this in production however.

**Comment by MikeMcC399** [comment]
In order for Bun to be integrated into `cypress-io/github-action` I would expect the following checklist items to all be checked off. The community could ignore the checklist and submit a PR and the Cypress team could decide to accept it. (I don't get to take this decision. It's just my opinion.)

## OS Support

- [X] Ubuntu
- [ ] Windows native (not WSL2)
- [X] macOS

## GitHub Actions Support

- [ ] Bun Callable from GitHub Actions [runs using](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions)
- [ ] Bun Shipped with [GitHub Actions Runner Images](https://github.com/actions/runner-images)

## Cypress Support

- [ ] Bun [supported by Cypress](https://docs.cypress.io/guides/getting-started/installing-cypress)
- [ ] Bun use by Cypress [documented](https://docs.cypress.io/)
- [ ] [Cypress Docker images](https://github.com/cypress-io/cypress-docker-images) include Bun (base, browsers, included)

**Comment by lundjrl** [comment]
> If somebody wants to use Bun with GitHub Actions, they can use the workflow [.github/workflows/single.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.github/workflows/single.yml) from the demo repo [cypress-io/cypress-example-kitchensink](https://github.com/cypress-io/cypress-example-kitchensink/) as a template (which does not rely on `cypress-io/github-action`).
> 
> 1. Replace `actions/setup-node@v3` by `npm install -g bun`
> 2. Change the cache lockfile from `package-lock.json` to `bun.lockb`
> 3. Add a new cache for `~/.bun`
> 4. Replace `npx` calls with `bun` calls
> 
> `bun install cypress` does not run the postinstall script, so you would also need to run `bun cypress install` manually.
> 
> I haven't seen any feedback from the Cypress team how they see Bun and I don't see any official support from Cypress for Bun either, so I would be cautious about using this in production however.

@MikeMcC399 Thank you for this, I greatly appreciate it!

**Comment by lundjrl** [comment]
@MikeMcC399 Yeah, it seems a little early for full Bun support. I guess I was under the impression that the infra behind Github Actions already supported it and Cypress was playing catch-up. I think it makes sense (if Cypress cares) to add an experimental Cypress Bun image but should in no way be ready for production with Windows support from the core bun team being so far behind.

**Comment by h2oearth** [comment]
IMO Bun is here to stay and some of us are using it, and will be nice if Cypress follow :-)

**Comment by MikeMcC399** [comment]
@h2oearth 

> IMO Bun is here to stay and some of us are using it, and will be nice if Cypress follow :-)

You should consider opening a feature request against Cypress on its [issue list](https://github.com/cypress-io/cypress/issues). Apparently nobody has made this suggestion so far.

The feature request here is for support of Bun by `cypress-io/github-action` which is only a small part of what would have to be done.

**Comment by h2oearth** [comment]
Will do @MikeMcC399 , cheers

**Comment by MarkAPhillips** [comment]
@h2oearth  can you refer to the feature request created - as would also like to see Cypress support bun - especially including a version in Docker that supports it - I am looking at migrating an app that uses to Cypress from npm to bun - as this may be a blocker.

**Comment by MikeMcC399** [comment]
@MarkAPhillips 

I cannot see any feature request for [Bun](https://github.com/oven-sh/bun) in the

- [`cypress` issue list](https://github.com/cypress-io/cypress/issues) or in the
- [`cypress-docker-images` issue list](https://github.com/cypress-io/cypress-docker-images)

so if you decided to submit a request yourself, you would not be duplicating any existing request.

**Comment by MikeMcC399** [comment]
- There is a compatibility issue between Bun `1.0.25` and Cypress `13.6.4` in that Bun fails to complete the Cypress postinstall script (effectively `bun cypress install`) if Node.js is not installed (see issue https://github.com/oven-sh/bun/issues/8658). This is not noticeable in a GitHub Actions environment because all [GitHub Actions Runner Images](https://github.com/actions/runner-images) have Node.js installed. The Cypress GitHub Action [cypress-io/github-action](https://github.com/cypress-io/github-action) entirely relies on Node.js, therefore it is not an issue with this action at this time, and for the foreseeable future.

**Comment by MikeMcC399** [comment]
- There still has not been any clean, simple request to the  [`cypress` issue list](https://github.com/cypress-io/cypress/issues) for Cypress to officially support Bun. This would need to come from somebody who wants it. Resolution of https://github.com/oven-sh/bun/issues/8658 by Bun would be a prerequisite, I imagine.

**Comment by MikeMcC399** [comment]
- Closing this feature request in favor of https://github.com/cypress-io/cypress/issues/28962. Please follow development in this main feature request.

**Comment by jennifer-shehane** [comment]
Bun support will be available in Cypress 15.17.0, so lookout out for this upcoming release.
