### ISSUE TITLE
Action does not work out of the box without a package.json file

### ISSUE THREAD

**Issue by agersant** [cypress-io/github-action#59]
Example output:

```
Run cypress-io/github-action@v1
  with:
    wait-on: http://localhost:5050
    spec: tests/initual-setup.js
    record: false
    config-file: cypress.json
    env: false
internal/fs/utils.js:220
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/runner/work/polaris-web/polaris-web/package-lock.json'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at Function.module.exports.309.hasha.fromFileSync (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:4486:54)
    at lockHash (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:2467:16)
    at getNpmCache (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:2475:16)
    at restoreCachedNpm (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:2518:21)
    at installMaybe (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:2816:5)
    at Object.104 (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:2837:1)
    at __webpack_require__ (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:22:30)
    at startup (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:37:19) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/runner/work/polaris-web/polaris-web/package-lock.json'
}
```

From https://github.com/agersant/polaris-web/commit/dcaf31ed3339aa6b49afb54e96e0ee790304744b/checks?check_suite_id=396158425

**Comment by agersant** [comment]
Note that I was able to work around this by adding the following step before the cypress action:
```
- name: Setup npm package
  run: npm init -y && npm install
```

**Comment by bahmutov** [comment]
@agersant can you describe your project structure? There is no `package.json` there at all? How does the action know what to install? Is there a `package.json` in a subfolder perhaps?

**Comment by agersant** [comment]
Thanks for looking at this @bahmutov! The project where I ran into this is a raw HTML page with a few <script/> tags adding functionality. There is no package.json anywhere or anything depending on node or npm. [Here is what the code looks like](https://github.com/agersant/polaris-web/tree/043e0f5b6d39bd6a0dc64396df1a7f6884182e98). I am not sure how the action decided what version of Cypress to install - I assumed it defaults to the latest?

As a side note, many tools other than Cypress are even less compatible with this setup so I caved and am migrating it to a more common structure :(

**Comment by bahmutov** [comment]
So, this action needs to install NPM dependencies, either using NPM or Yarn - but it needs to know what versions to use, that's why you need `package.json`. You can use `cypress/included:...` Docker image instead directly inside GH Actions (you don't need this cypress/action at all).

See https://github.com/bahmutov/cypress-gh-action-included

Here is example workflow file
```yml
name: included
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # Docker image with Cypress pre-installed
    # https://github.com/cypress-io/cypress-docker-images/tree/master/included
    container: cypress/included:3.8.3
    steps:
      - uses: actions/checkout@v1
      - run: cypress run
```

**Comment by agersant** [comment]
Thank you so much!

**Comment by sabin-bhattarai-cko** [comment]
![image](https://user-images.githubusercontent.com/47529368/75154549-d4828d00-5705-11ea-92fe-f65f01ee8516.png)

Getting this error. I do have a package.json file in the working directory.
If I push the package-lock.json file - It works. Any help would be great.

**Comment by MartinDawson** [comment]
Same problem as @sabin-bhattarai-cko. Config file is the same as the basic setup on ReadMe.md too.
