### ISSUE TITLE
use yarn 2 command

### ISSUE THREAD

**Issue by Himself65** [cypress-io/github-action#591]
```
/usr/local/bin/yarn --frozen-lockfile
➤ YN0050: The --frozen-lockfile option is deprecated; use --immutable and/or --immutable-cache instead
```

**Comment by agungkes** [comment]
You can change the install command by following the instructions below

https://github.com/cypress-io/github-action#custom-install-command

**Comment by brandonchinn178** [comment]
Yes, you can specify the install command, but the default install command in the github action should be `--immutable`. Anyone not using the latest Yarn should use `custom-install` to use the old flag

**Comment by Himself65** [comment]
> You can change the install command by following the instructions below
> 
> https://github.com/cypress-io/github-action#custom-install-command

This works for me. Thanks!
