### ISSUE TITLE
Caching node_modules

### ISSUE THREAD

**Issue by hornta** [cypress-io/github-action#592]
Our install job is taking 5 minutes to perform the `npm ci`. It would be good to cache node_modules based on package-lock.json and perhaps also on the node version to minimize the time it takes to run tests. Is this a good idea?

**Comment by dannyskoog** [comment]
IMHO this should be up to the users to set up themselves.

**Comment by MikeMcC399** [comment]
https://github.com/actions/cache/blob/main/examples.md#node---npm

says:

"Note: It is not recommended to cache node_modules, as it can break across Node versions and won't work with npm ci"

**Comment by dannyskoog** [comment]
> https://github.com/actions/cache/blob/main/examples.md#node---npm
> 
> 
> 
> says:
> 
> 
> 
> "Note: It is not recommended to cache node_modules, as it can break across Node versions and won't work with npm ci"

Correct. But including the Node version in the cache key + skip running npm ci on cache hit works great from experience 👍

**Comment by jaffrepaul** [comment]
Closing this based on the subjectivity of user interaction. Thank you for opening an issue here!
