### ISSUE TITLE
Cypress-io plugin does not split up the test cases to run in parallel when using custom test command that uses CYPRESS_INCLUDE_TAGS

### ISSUE THREAD

**Issue by sarathk-blink** [cypress-io/github-action#594]
Cypress-io plugin does not split up the test cases to run in parallel when using custom test command that uses CYPRESS_INCLUDE_TAGS.

When I pass the spec folder, I can see that the tests ar being split. But when use command that's specified in package.json with specific set of tags across the project, the plug in does not split the tests across the parallel threads, instead runs all the tests in all the threads.

**Comment by MikeMcC399** [comment]
Closing, since this is a stale issue. If there is new information available, then we can re-open.
