### ISSUE TITLE
[FEATURE] Support Merge Queue

### ISSUE THREAD

**Issue by conversayShawn** [cypress-io/github-action#597]
Feature request for GH Actions [Merge Queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue) support

**Comment by admah** [comment]
@conversaShawn you should be able to try this without any changes to the code. You should be able to add `merge_group` to the trigger like:

`on: [push, merge_group]`

Do you have a use-case that you could share?

**Comment by MikeMcC399** [comment]
This request was answered. No changes are necessary.
