### ISSUE TITLE
Upgrade to latest actions/cache

### ISSUE THREAD

**Issue by dhadka** [cypress-io/github-action#60]
Please consider upgrading to the latest version of actions/cache, specifically v1.1.0.  This version increases the upload cap (400 MBs -> 2 GBs) and also parallelizes the upload to reduce upload time.

**Comment by zamaraevk** [comment]
@bahmutov any plans to make this update?

I am also getting `##[warning]Cache size of 769268131 bytes is over the 400MB limit, not saving cache.` and would love if we can have latest `actions/cache`

**Comment by dhadka** [comment]
Also, we recently converted it to a module (`@actions/cache`) as part of the Actions toolkit - https://github.com/actions/toolkit, so it should be much easier to integrate.

**Comment by dlavrenuek** [comment]
The latest Cypress version constantly hits the 400 mark in our CI, so the e2e tests take about 30 seconds to 1 minute longer just because of the outdated cache handling. Please remove the hardcoded limit.
