### ISSUE TITLE
Update `@actions/core` dependency to >=1.10.0 to avoid deprecation warning

### ISSUE THREAD

**Issue by dennisjlee** [cypress-io/github-action#613]
In a GitHub action where I use `cypress-io/github-action@v4`, I'm seeing this warning: 

```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

I think this would be addressed by upgrading `@actions/core` in package.json. 

There is one usage of the `setOutput` method in the codebase, [here](https://github.com/cypress-io/github-action/blob/master/index.js#L750).

**Comment by MikeMcC399** [comment]
The warning says "The `set-output` command is deprecated and will be disabled soon." which makes it sound urgent, however the text in the link https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ quotes the date of June 1, 2023:

"October 11, 2022
To avoid untrusted logged data to use set-state and set-output workflow commands without the intention of the workflow author we have introduced a [new set of environment files](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files) to manage state and output.

Starting today runner version 2.298.2 will begin to warn you if you use the save-state or set-output commands via stdout. We are monitoring telemetry for the usage of these commands and plan to fully disable them on 31st May 2023. Starting 1st June 2023 workflows using save-state or set-output commands via stdout will fail with an error."

Nevertheless it would be good to have cypress-io/github-action updated soon to avoid the warning appearing.

**Comment by jpita** [comment]
is this fixed or still wip?

**Comment by lwhiteley** [comment]
> is this fixed or still wip?

there are no pull requests addressing the issue currently
the package.json version of @actions/core has not been updated either

https://github.com/cypress-io/github-action/blob/master/package.json#L35

**Comment by piotrekkr** [comment]
Possible fix in #621

**Comment by piotrekkr** [comment]
@MikeMcC399 Seems like I did not know that I also need to rebuild dist files. Fix is in #638

**Comment by piotrekkr** [comment]
@MikeMcC399 I used `piotrekkr/github-action@update-dist-files` and I didn't get any warnings in GitHub from cypress action

**Comment by MikeMcC399** [comment]
@piotrekkr 

- Thanks for the follow-on PR #638!
- I checked again using the merged version and everything is fine with `uses: cypress-io/github-action@v4`! No more warning message.
