### ISSUE TITLE
use viewport in github actions

### ISSUE THREAD

**Issue by SaadUsmanitk** [cypress-io/github-action#635]
is there any way to use set viewport in github actions?

**Comment by kryshenp** [comment]
I've solved it by creating a separate config file named cypress-ci.config.ts, which is identical to cypress.config.ts, but I removed viewportHeight, viewportWidth parameters from there.


In my github action I can set my own `viewportHeight` & `viewportWidth`.  config file is my cypress-ci.config.ts, that doesn't contain  viewportHeight, viewportWidth parameters.
`- name: Cypress run
        uses: cypress-io/github-action@032c1ed6197b579a85b6759a05daa6370ea71f8b # v4.2.1
        env:
          CYPRESS_BASE_URL: ${{ inputs.base-url }}
        with:
          browser: ${{ inputs.browser }}
          spec: ${{ inputs.specs }}
          working-directory: cypress
          install-command: npm ci
          headed: ${{ inputs.headed }}
          config-file: cypress-ci.config.ts
          config: video=${{ inputs.video == 'true' && 'true' || 'false' }},retries=2,viewportHeight=1243,viewportWidth=1792`

Of course, you could set  `viewportHeight` & `viewportWidth` from workflow input, for example:
 `config: viewportHeight=${{ github.event.inputs.viewportHeight }},viewportWidth=${{ github.event.inputs.viewportWidth }}`

**Comment by MikeMcC399** [comment]
@SaadUsmanitk 

Did the answer from @kryshenp help you?

There is nothing specific in `github-action` regarding viewports.

**Comment by MikeMcC399** [comment]
Closing as this is a stale issue.
