### ISSUE TITLE
Warning "The `set-output` command is deprecated and will be disabled soon" still persists after action upgrade to v4.2.1

### ISSUE THREAD

**Issue by kryshenp** [cypress-io/github-action#640]
Release 4.2.1 https://github.com/cypress-io/github-action/releases/tag/v4.2.1 should fix deps: set-output command warnings from GitHub caused by @actions/core package to be lower than v1.10.0. 

In my workflow I tried 
`cypress-io/github-action@v4.2.1`, `cypress-io/github-action@a66d9963a59d417607160127678cba80faf72cf4`, and `cypress-io/github-action@032c1ed6197b579a85b6759a05daa6370ea71f8b` , but I still see the following warning message:
 _Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/_ 

Does anybody have the same result as I do?

**Comment by jaredwebber** [comment]
I'm still seeing the warning message as well. It looks like the `actions/cache@v1.0.11` dependency may need to be updated to `actions/cache@v3.0.11` as that's where `actions/cache` was updated to use `actions/core@v1.10.0` ([`actions/cache` PR #956](https://github.com/actions/cache/pull/956)).

**Comment by kryshenp** [comment]
Maybe it's related to: https://github.com/cypress-io/github-action/issues/613. They still have related PR opened: https://github.com/cypress-io/github-action/pull/638

**Comment by MikeMcC399** [comment]
@kryshenp 

- PR #638 is closed now and [v4.2.2](https://github.com/cypress-io/github-action/releases/tag/v4.2.2) is released
- I checked with `uses: cypress-io/github-action@v4` and I no longer get a deprecation warning message
