### ISSUE TITLE
Enable testing serverless locally

### ISSUE THREAD

**Issue by muratkeremozcan** [cypress-io/github-action#647]
Start-server-and-test has a new feature that enables testing against localhost in case of Auth issues (403). 403 is probable when serving a lambda locally. 

Here is the PR for the feature https://github.com/bahmutov/start-server-and-test/pull/343.

Would you update the GHA to support this new feature? It will enable testing serverless apps locally, without having to deploy.

**Comment by muratkeremozcan** [comment]
We added a health check endpoint to our implementation to work around the challenge. Things are in good shape in CI. 

The parity between star-server-and-test plugin and Cypress GHA can be deprioritized.

**Comment by MikeMcC399** [comment]
@muratkeremozcan 

Do you still suggest that there is a need for `github-action` to provide a `wait-on` option for HTTP `403` Forbidden?

There haven't been any other requests for this.

**Comment by MikeMcC399** [comment]
Closing, since there was no further feedback,
