### ISSUE TITLE
Deprecated Ubuntu 18.04 used in example workflows

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/github-action#648]
## Where to find the issue

There are three workflows using the deprecated runner Ubuntu 18.04:

- [.github/workflows/example-basic.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-basic.yml)
- [.github/workflows/example-basic-pnpm.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-basic-pnpm.yml)
- ~~[.github/workflows/example-firefox.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-firefox.yml)~~ (Fixed)

## Describe the issue

GitHub workflows are using the deprecated [ubuntu-18.04](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu1804-Readme.md) runner image.

- GitHub [ubuntu-18.04](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu1804-Readme.md) runner is deprecated and will be fully unsupported by 2023-04-01.

- GitHub [Ubuntu-latest workflows will use Ubuntu-22.04](https://github.com/actions/runner-images/issues/6399).

## Suggestion

- PR https://github.com/cypress-io/github-action/pull/643 incidentally addresses the issue with [.github/workflows/example-firefox.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-firefox.yml) by updating to `ubuntu-latest`. Edit: now changed to `ubuntu-20.04`.

Update the other two workflows to use `ubuntu-22.04`:

- [.github/workflows/example-basic.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-basic.yml)
- [.github/workflows/example-basic-pnpm.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-basic-pnpm.yml)

In addition update:

- [actions/checkout@v2](https://github.com/actions/checkout) to v3

Consider for these two workflows if it is necessary to retain testing of two different versions of Ubuntu. In general it may be advantageous for all workflows to standardize on `ubuntu-latest`.

**Comment by jaffrepaul** [comment]
> I would offer to submit a PR for this, however I am unsure if there is capacity on the maintainer side of this repository currently which could process PR submission. How are things looking in general here from the maintenance side?
> 
> The more I look, the more I see things which need updating!

Thank you @MikeMcC399. I learned that pinning these Ubuntu runners to a specific version was to help with [this issue](https://github.com/cypress-io/github-action/issues/518). However, as you've noted this is now becoming outdated. `-latest` is still transitioning to `ubuntu-22.04`. So for the time being, we could update the pinned versions to latest and update the test which covers one version behind accordingly.

There is a new team of two aiming to get ALL Cypress tools and plugins back up to date. There are a number of things needing attention in the GHA. This will take some time but I encourage you to open PRs where you can!

**Comment by MikeMcC399** [comment]
@jaffrepaul 

> This will take some time but I encourage you to open PRs where you can!

I'm happy to hear that there is a team in place and thank you for your feedback and encouragement! I will start with a documentation update, to make a small improvement and to test my understanding of the submission process.

I'll follow up with a PR to fix the deprecated Ubuntu 18.04 version, however I would like to wait until you have merged your PR to fix failing workflows, so that I would be working from a clean base which is showing no errors. There is still plenty of time until Ubuntu 18.04 completely runs out of support.

**Comment by MikeMcC399** [comment]
@jaffrepaul 

To align with your change in https://github.com/cypress-io/github-action/pull/643 I would not use `ubuntu-latest`, instead most of the sub-tests would continue to run under `ubuntu-20.04`. For the sub-test groups running a combination of 18.04/20.04 I would change that to run 20.04/22.04.

If you can give me your confirmation that the above is what is required, then I will start the PR work.

**Comment by jaffrepaul** [comment]
@MikeMcC399 Agreed!

**Comment by MikeMcC399** [comment]
@jaffrepaul 

- I have submitted https://github.com/cypress-io/github-action/pull/651 to cover the first correction. The workflows need approval again.
- Presumably each new PR will need individual workflow approval until one PR from me has been merged into `master` and I will get GH Contributor status for this repository.
- Due to the above I have held back the PR to correct `example-basic-pnpm`. The branch https://github.com/MikeMcC399/github-action/tree/update/example-basic-pnpm is ready to open a PR from.

**Comment by MikeMcC399** [comment]
- PR https://github.com/cypress-io/github-action/pull/651 is ready for review. The tests have run successfully 🙂 .

**Comment by MikeMcC399** [comment]
- PR #666 now submitted for the second part of this issue.

I have left both PRs in Draft state, since they only solve a deprecation **warning**. The other PRs which solve workflow failures should be looked at first.

**Comment by MikeMcC399** [comment]
PRs are now ready for review

**Comment by MikeMcC399** [comment]
The following two PRs have been merged and this issue is therefore resolved:

- #651 
- #666
