### ISSUE TITLE
Noisy HTTP / XHR requests in Cypress logs

### ISSUE THREAD

**Issue by docmars** [cypress-io/github-action#649]
### Environment
- cypress v10.9.0
- cypress-io/github-action v4

### Summary
I'm not sure which version this started happening in, but I noticed within the last 2-3 weeks that every HTTP request is being logged between `it` blocks, making it very hard to navigate Cypress CI logs in GH Actions summaries. This not only makes them super long, but difficult to pinpoint failures + reasons.

At a glance, I wasn't able to find any configuration options in Cypress or the action to keep the noise down. There is a related issue (https://github.com/cypress-io/cypress/issues/7362) in the Cypress repo with similar complaints where there's too much HTTP noise in the command log, and unfortunately the only workarounds are janky and unofficial, causing important functionality like stubbing/interception to quit working properly, or needing to introduce super gross jQuery hackery to hide what could be put behind a configuration option.

Any help / suggestions would be appreciated!

---

Here's an example of what we're seeing, with no configuration changes since we started seeing this:

<img width="802" alt="image" src="https://user-images.githubusercontent.com/758090/206235325-685f0662-c8a5-4a9f-89e7-02c4e9a62906.png">

**Comment by kryshenp** [comment]
I might be wrong and just speculating but the issue could be somewhere outside the step that uses cypress-io/github-action. 

I have 2 different workflows with a slightly different setups of the app but with completely identical `uses: cypress-io/github-action@v5` cypress run step. In the output of one of them, I see the annoying noise that you're mentioning. The other one gives clear classic output.

**Comment by docmars** [comment]
@kryshenp Huh, strange — I'm asking my team if they enabled any global verbose logging for HTTP requests or anything like that in our project. In your case, are these workflows in separate repos, or are there any other known differences like a different Linux image for the action, or different Cypress configs in each app?

**Comment by kryshenp** [comment]
@docmars , all our workflows are in the same repo. I did some investigation and found in the workflow run history the exact workflow where this logging started to happen. I compared all logs and settings with a previous clear workflow run and didn't find any changes in workflow setups, installed packages, or config file - literally nothing. I even restored both deleted branches and ran my workflow against them again, and in both runs, they produced these unwanted HTTP logs. The only conclusion I could have here is that GitHub implemented some new settings under the hood that are out of our control and visibility. The first time this issue occurred for us was on November 9th.

**Comment by docmars** [comment]
@kryshenp I found the culprit on my end — it's a real head-slapper too:

Vercel's [`serve`](https://github.com/vercel/serve) package we use to start a web server for Cypress to use in CI has now defaults to logging all HTTP requests when it gets hit.

They offer an option in `14.1.2` to suppress these logs by passing `--no-request-logging`, which has worked magically!

Closing this thread for now, but feel free to re-open if you suspect there is a different cause for your noisy logs. When in doubt, check your web server used in CI.

**Comment by MikeMcC399** [comment]
@docmars 

Thanks for sharing!

I have an open PR here (https://github.com/cypress-io/github-action/pull/658) which also updates one of the examples to use [serve](https://github.com/vercel/serve) 14.1.2. Now you point it out, I also notice the new log lines (see run [3679237962](https://github.com/cypress-io/github-action/actions/runs/3679237962) => start => Cypress tests, Lines 58-60). Since the example test is very simple there weren't many additional logging lines displayed.
