### ISSUE TITLE
Does cypress-io/github-action v4 only have support until v10 of Cypress?

### ISSUE THREAD

**Issue by jyiwm** [cypress-io/github-action#652]
It seems like Cypress v10 is the latest supported version but I just wanted to be sure. I couldn't find anything explicitly confirming this.

**Comment by MikeMcC399** [comment]
@jyiwm

Are you finding any issues with github-actions running under Cypress 11 or 12?

The README documentation needs updating as the latest version of github-actions is in fact v5.  (See https://github.com/cypress-io/github-action/releases/tag/v5.0.0 released a few days ago). If you are starting anything new then you should probably use v5, not v4.

If would be good if the README contained some compatibility information for github-action (GHA) version, against Cypress version and Node.js version.

**Comment by MikeMcC399** [comment]
@jyiwm 

If the [v10 examples](https://github.com/cypress-io/github-action/tree/master/examples/v10) are updated to use Cypress 12.2.0 then all the [workflows](https://github.com/cypress-io/github-action/tree/master/.github/workflows) using the latest version of [cypress-io/github-action](https://github.com/cypress-io/github-action) continue to be successful. So there is no apparent problem moving from Cypress 10.0.0 to Cypress 12.2.0 with these examples.

**Comment by jyiwm** [comment]
Okay thanks, for the info, I'll close this.

**Comment by MikeMcC399** [comment]
- PR https://github.com/cypress-io/github-action/pull/725 has updated all examples
