### ISSUE TITLE
Action immediately errors out

### ISSUE THREAD

**Issue by agersant** [cypress-io/github-action#67]
Hello!
I've been happily using the Cypress github actions for a few days and it has stopped working all of a sudden, with no changes in my CI setup.

Runs immediately fail with: 
![image](https://user-images.githubusercontent.com/817256/72958238-7146b900-3d5b-11ea-99bb-2332819f11e8.png)

Example failed run: https://github.com/agersant/polaris-web/runs/404434946 (I re-ran it several times to rule out flukes)
Previous successful run: https://github.com/agersant/polaris-web/commit/7d3972d617c088d2189cddfc28a6761b743c23f3/checks?check_suite_id=408103643

Is this an issue with the action or with Github actions in general? Many thanks in advance!

**Comment by Sebastian-Haehnlein** [comment]
workaround: 

```runs-on: ubuntu-16.04```

**Comment by Niceplace** [comment]
Same situation here, although the error message is a bit different

```

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.

----------

Command failed: /home/runner/.cache/Cypress/3.8.2/Cypress/Cypress --no-sandbox --smoke-test --ping=1

----------

Platform: linux (Ubuntu Linux - 18.04)
Cypress Version: 3.8.2
25hError: The process '/opt/hostedtoolcache/node/10.18.1/x64/bin/npx' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:894:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:877:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:777:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
##[error]The process '/opt/hostedtoolcache/node/10.18.1/x64/bin/npx' failed with exit code 1
##[error]Node run failed with exit code 1
##[debug]Finishing: Cypress run
```

It worked for a few days and then started happening a few days ago. I will try the workaround suggested by @Sebastian-Haehnlein and report back.

**Comment by Niceplace** [comment]
Oh, it's in the README lol: https://github.com/cypress-io/github-action#important @agersant

**Comment by agersant** [comment]
Thank you! I did look for recent issues before filing this but missed the readme update!
