### ISSUE TITLE
Example uses Docker image with end-of-life Node.js 12

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/github-action#680]
## Problem description

The documentation examples

- [Docker image](https://github.com/cypress-io/github-action#docker-image) 
- [Firefox](https://github.com/cypress-io/github-action#firefox)

use GHA running in a Cypress Docker Image

[cypress/browsers:node12.13.0-chrome78-ff70](https://github.com/cypress-io/cypress-docker-images/tree/master/browsers/node12.13.0-chrome78-ff70).

Although this docker image is still available, Node.js 12 is in the [End-of-Life Releases](https://github.com/nodejs/release#end-of-life-releases) list and entered End-of-Life on 2022-04-30 so it is no longer a good active example of a Cypress Docker image.

## Expected behavior

Any documentation examples which show GHA running in a Cypress Docker Image should select an image with a Node.js in active LTS (Long Term Support) state. This is currently Node.js 18. See [Node.js Release Schedule](https://github.com/nodejs/release#release-schedule).

## Suggested Fix

Use the Cypress Docker image [cypress/browsers:node18.12.0-chrome106-ff106](https://github.com/cypress-io/cypress-docker-images/tree/master/browsers/node18.12.0-chrome106-ff106) in the above documentation examples instead of the Node.js 12 Docker image.

**Comment by MikeMcC399** [comment]
- PR https://github.com/cypress-io/github-action/pull/681/files is submitted to resolve this issue

**Comment by MikeMcC399** [comment]
The Cypress docs on https://docs.cypress.io/guides/continuous-integration/github-actions#Testing-in-Chrome-and-Firefox-with-Cypress-Docker-Images should also be aligned.

**Comment by jaffrepaul** [comment]
> 

Thanks, I added an issue to the Docs repo.

**Comment by MikeMcC399** [comment]
- The documentation issue is https://github.com/cypress-io/cypress-documentation/issues/5013.

**Comment by MikeMcC399** [comment]
The issue in the repo is resolved. The documentation issue in the main Cypress repo is tracked separately (see ^).
