### ISSUE TITLE
v10 examples do not use latest version 12.x

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/github-action#684]
## Current situation

Example workflows in [examples/v10](https://github.com/cypress-io/github-action/tree/master/examples/v10) are configured to use [Cypress 10.0.0](https://docs.cypress.io/guides/references/changelog#10-0-0), released on June 1, 2022. Since then, Cypress 11 and Cypress 12 have been released. The version is stored in `package.json` files, `package-lock.json`, `yarn.lock` and `pnpm-lock.yaml` files.

## Suggested change

Update all v10 example workflows in [examples/v10](https://github.com/cypress-io/github-action/tree/master/examples/v10) to use the latest Cypress version according to the [Cypress changelog](https://docs.cypress.io/guides/references/changelog).

## Benefits

Updating the v10 examples to use the latest Cypress version provides increased confidence that GHA is up-to-date and compatible with the latest Cypress major version (12).

**Comment by MikeMcC399** [comment]
- I already successfully tested updating the v10 examples to use Cypress 12, however I will hold back on submitting a PR until PR https://github.com/cypress-io/github-action/pull/673 is completed to avoid getting into `package-lock.json` and `yarn.lock` conflicts. Also it would be good to hear if updating is actually wanted or not.

**Comment by MikeMcC399** [comment]
@jaffrepaul 

Any feedback on this suggestion? It makes sense to me to update.

**Comment by jaffrepaul** [comment]
Agreed. We're working to get all of our ancillary tools and repos to use the latest version of Cypress. Certainly applies here. We'll need to land on some appropriate naming conventions, i.e the `/v10` folder, etc.

**Comment by MikeMcC399** [comment]
@jaffrepaul 

> We'll need to land on some appropriate naming conventions, i.e the /v10 folder, etc.

The naming of [examples/v10](https://github.com/cypress-io/github-action/tree/master/examples/v10) would be misleading after updating the examples to Cypress 12.x. So I follow your thinking about settling on a different naming convention.

One possibility would be:
- [examples/v9](https://github.com/cypress-io/github-action/tree/master/examples/v9) - leave unchanged
- [examples](https://github.com/cypress-io/github-action/tree/master/examples)  - remove the v10 level and move it up one level for 12.x and any later versions

If there is a prospect in the future of another breaking change in Cypress which could create the need for another complete set of compatible examples, then it would be better to keep the v10 level and rename `v10` in [examples/v10](https://github.com/cypress-io/github-action/tree/master/examples/v10) to, for example, one of the following:
- v1x (which would cover Cypress versions 10-19)
- v1n
- current
- latest

Removing the v10 level would be my first choice and renaming v10 to v1x would be my second choice.

**Comment by MikeMcC399** [comment]
@jaffrepaul 

If there is a change in the v10 directory I would suggest to split the changes into two separate PRs:

1. No change to v10 directory, update Cypress to latest 12.x 
2. Change the directory name or location for the 12.x tests. This also affects documentation.

That would make it easier for testing and review.

**Comment by MikeMcC399** [comment]
- [ ] PR #725 is now submitted to update the examples to Cypress 12.3.0

**Comment by MikeMcC399** [comment]
Next step:
- Move the Cypress 12.3.0 examples from [examples/v10](https://github.com/cypress-io/github-action/tree/master/examples/v10) to [examples](https://github.com/cypress-io/github-action/tree/master/examples) and eliminate the  [examples/v10](https://github.com/cypress-io/github-action/tree/master/examples/v10) directory, since the label `v10` no longer fits the v12 version (or any future possible later major version v13, etc.).
