### ISSUE TITLE
v9 examples do not use latest 9.x version 9.7.0

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/github-action#685]
## Current situation

Example workflows in [examples/v9](https://github.com/cypress-io/github-action/tree/master/examples/v9) are configured to use [Cypress 9.6.1](https://docs.cypress.io/guides/references/changelog#9-6-1). This version is older than the latest Cypress 9.x version, which is [Cypress 9.7.0](https://docs.cypress.io/guides/references/changelog#9-7-0). The version is stored in `package.json` files, `package-lock.json`, `yarn.lock` and `pnpm-lock.yaml` files.

## Suggested change

Update all v9 example workflows in [examples/v9](https://github.com/cypress-io/github-action/tree/master/examples/v9) to use [Cypress 9.7.0](https://docs.cypress.io/guides/references/changelog#9-7-0).

## Benefits

The latest version of Cypress 9.x, before the release of Cypress 10 with its breaking changes, is [Cypress 9.7.0](https://docs.cypress.io/guides/references/changelog#9-7-0). Updating the examples to this version ensures that the examples will have all available fixes from the 9.x stream available to them.

**Comment by MikeMcC399** [comment]
Please let me know if a PR would be welcome for this update.

**Comment by MikeMcC399** [comment]
@jaffrepaul 

Same question here. Should the v9 examples be updated to the latest 9.x i.e. 9.7.0?

**Comment by jaffrepaul** [comment]
Yes, that'd be ideal.

**Comment by MikeMcC399** [comment]
@jaffrepaul 

Thank you for your agreement to update to 9.7.0! 

To avoid conflicts I have dropped the priority on

- https://github.com/cypress-io/github-action/pull/708

and I have put the above PR into Draft state whilst I submit a PR to update to 9.7.0. I will need to manually rebase it after the update to 9.7.0 before activating it again.

**Comment by MikeMcC399** [comment]
- PR https://github.com/cypress-io/github-action/pull/724 is submitted to update all [Legacy configuration](https://docs.cypress.io/guides/references/legacy-configuration) (v9) examples to use Cypress 9.7.0.
