### ISSUE TITLE
Update to Ubuntu 22.04 as standard

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/github-action#696]
This is a suggestion to update the version of Ubuntu generally used in the workflows from `ubuntu-20.04` to `ubuntu-22.04`, given that `ubuntu-latest` is now equivalent to `ubuntu-22.04` for all repositories.

## Current situation

The [example workflows](https://github.com/cypress-io/github-action/tree/master/.github/workflows) generally run on `ubuntu-20.04`.

GitHub completed the [migration of ubuntu-latest](https://github.com/actions/runner-images/issues/6399) to [ubuntu-22.04](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md) on December 15, 2022. [ubuntu-20.04](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md) is still available.

## Suggested change

Convert the [example workflows](https://github.com/cypress-io/github-action/tree/master/.github/workflows) which currently only run on [ubuntu-20.04](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md) to instead run on [ubuntu-22.04](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md).

Also update [main.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/main.yml) to run on [ubuntu-22.04](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md).

For consistency and clarity, change [example-component-test.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-component-test.yml) to run on [ubuntu-22.04](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md) instead of `ubuntu-latest`.

Change documents [DEVELOPMENT.md](https://github.com/cypress-io/github-action/blob/master/DEVELOPMENT.md) and [README.md](https://github.com/cypress-io/github-action/blob/master/README.md) to specify [ubuntu-22.04](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md) explicitly instead of `ubuntu-latest`.

The following two workflows run on both [ubuntu-20.04](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md) and [ubuntu-22.04](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md), so they should not be changed. They continue to ensure that both these currently supported GitHub Ubuntu runner environments are tested:

- [example-basic.yml](https://github.com/cypress-io/github-action/blob/b23f22bd72e8c7fe1afab8e8989cec8431998f6f/.github/workflows/example-basic.yml)
- [example-basic-pnpm.yml](https://github.com/cypress-io/github-action/blob/3ab3d50a051ce79152c7b89a88ce45f6e283a2cc/.github/workflows/example-basic-pnpm.yml)

## Benefits

Moving the default Ubuntu version in the example workflows to [ubuntu-22.04](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md), which now corresponds to `ubuntu-latest`, ensures that the different examples are pre-tested in this latest [GitHub runner](https://github.com/actions/runner-images) Ubuntu environment.

Specifying an explicit Ubuntu version instead of using `ubuntu-latest` makes it clearer exactly which version of Ubuntu is being tested. The [migration of ubuntu-latest](https://github.com/actions/runner-images/issues/6399) from `ubuntu-20.04` to `ubuntu-22.04` took space over a period of over two months, during which time `ubuntu-latest` was interpreted on an individual basis, meaning it was volatile over a significant period of time.

---

*Note: [ubuntu-18.04](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu1804-Readme.md) is deprecated, is no longer used in this repository (see issue https://github.com/cypress-io/github-action/issues/648), and no longer needs to be considered here.*

**Comment by MikeMcC399** [comment]
@jaffrepaul 

Waiting for feedback on this suggestion.

**Comment by jaffrepaul** [comment]
This looks good to me. 

I've learned that we historically had avoided using `-latest` because of [this sort of error](https://github.com/cypress-io/github-action/issues/518). This tends to happen more whenever there is an Ubuntu or Chrome release. So pinning it to a version has multiple benefits.

**Comment by MikeMcC399** [comment]
@jaffrepaul 

Thank you very much for your agreement!

- PR #720 implements this suggestion for workflows and documentation

According to https://ubuntu.com/about/release-cycle Ubuntu LTS or ‘Long Term Support’ releases are published every two years in April. This means that the next one should be 24.04 in April 2024, leaving another year and a bit until this will need a new review.

**Comment by MikeMcC399** [comment]
- PR https://github.com/cypress-io/github-action/pull/723 needed to completely resolve this issue, since there was one example still using `ubuntu-18.04`.
