### ISSUE TITLE
On github actions does chrome headless improve execution time?

### ISSUE THREAD

**Issue by alexbjorlig** [cypress-io/github-action#70]
It would be awesome if the readme of this repo could include a short description, explaining why one would consider using the chrome headless option.

**Comment by jennifer-shehane** [comment]
This repo is only for issues relating to Cypress GitHub actions specifically. If you want to open an issue on our main documentation (which would cover uses of chrome --headless more generally for everyone using Cypress), you can open it [here](https://github.com/cypress-io/cypress-documentation/issues/new). This issue will be closed in this repository.

**Comment by alexbjorlig** [comment]
i think the key here is 

> ... improve execution time?

In other words this question is related specifically to Cypress GitHub action, i.e. does it run faster with --headless.

Would you help me get this question answered here 🙏

**Comment by jennifer-shehane** [comment]
I'm still not sure why this would be specific to a GitHub action. Where are you seeing this `improve execution time?` written from our team?

I'm not aware of any improved execution time between chrome --headless versus headed.

You can review the original issue for chrome headless to see some of the reasons users wanted support for this here: https://github.com/cypress-io/cypress/issues/832

**Comment by alexbjorlig** [comment]
As a cypress customer using Github actions running Cypress, I am interested in getting the fastest possible execution of Cypress. I don't know if the `headless` options matters here, that's why I asked 🙃

Setting up Cypress with CI is tough work - and getting support is not easy either, but thanks for helping to answer the question. Means a lot 😊
