### ISSUE TITLE
Restart a specific job executes all test cases

### ISSUE THREAD

**Issue by nitishvu** [cypress-io/github-action#719]
Hi

I'm using spot instances on GCP to perform my tests according to the technique listed below.
I have to restart the entire workflow if one of these instances is preempted during test execution. If I restart the failed run, all test cases are being executed in one VM, which takes a lot of time. Is it possible to restart one run to only execute the test cases that are assigned to the preempted VM?

```
    strategy:
      matrix:
        machines: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
```

**Comment by MikeMcC399** [comment]
@nitishvu 

- Your question seems to be related to the open issue https://github.com/cypress-io/github-action/issues/531

**Comment by MikeMcC399** [comment]
- Closing in favor of #531
