### ISSUE TITLE
Cypress failed to start

### ISSUE THREAD

**Issue by luludan** [cypress-io/github-action#72]
Have been using this action for the last few months and everything has been running fine, today have been getting this error with no other output. 

Have tried with v1, v1.19.0 and v1.20.0

```
25l[18:39:44]  Verifying Cypress can run /home/runner/.cache/Cypress/3.8.0/Cypress [started]
[18:39:45]  Verifying Cypress can run /home/runner/.cache/Cypress/3.8.0/Cypress [failed]
25hCypress failed to start.
```

**Comment by bahmutov** [comment]
@luludan I believe this is the GH Ubuntu switch issue as we have just fixed, see this comment https://github.com/cypress-io/github-action/blob/master/README.md#important

**Comment by luludan** [comment]
@bahmutov Thanks for the quick reply!

Upgraded Cypress to 3.8.3 and is now working again fine 👍
