### ISSUE TITLE
CHANGELOG not produced by release process

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/github-action#722]
## Problem description

Although the `release` job in the [.github/workflows/main.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/main.yml) is set up with the `extra_plugins:` parameter `@semantic-release/changelog` no changelog is generated:

```yaml
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          branch: master
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
```

## Steps to reproduce the issue

View https://github.com/cypress-io/github-action and note that there is no file `CHANGELOG.md` present.

View the [release log](https://github.com/cypress-io/github-action/actions/runs/3735556607/jobs/6338967733) for PR https://github.com/cypress-io/github-action/pull/677 which triggered release [v5.0.1](https://github.com/cypress-io/github-action/releases/tag/v5.0.1)  automatically.

Note that no changelog is called. If there were, then it would appear as:

```text
 › ℹ  Start step "prepare" of plugin "@semantic-release/changelog"
```

## Expected behavior

When a release is generated through [cycjimmy/semantic-release-action](https://www.npmjs.com/package/@cycjimmy/semantic-release-action) then a `CHANGELOG.md` should be created or updated in https://github.com/cypress-io/github-action.

## Analysis

The documentation for [cycjimmy/semantic-release-action: extra_plugins](https://github.com/cycjimmy/semantic-release-action#extra_plugins) says:

"When using this option, please make sure that these plugins are also mentioned in your [semantic release config's plugins](https://semantic-release.gitbook.io/semantic-release/usage/configuration#plugins) array."

Referring to the related documentation about semantic-release's [configuration file](https://semantic-release.gitbook.io/semantic-release/usage/configuration#configuration-file), none of the options has been set:

- A .releaserc file, written in YAML or JSON, with optional extensions: .yaml/.yml/.json/.js
- A release.config.js file that exports an object
- A release key in the project's package.json file

This is the reason that no `CHANGELOG.md` has been created.

## Suggested Fix

Create the file https://github.com/cypress-io/github-action/.releaserc with the contents:

```json
{
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/changelog",
    "@semantic-release/npm",
    "@semantic-release/github",
    "@semantic-release/git"
  ]
}
```

This also fixes the issue that @semantic-release/git does not run, for the same reason that it is also not correctly configured.

## References

- https://github.com/semantic-release/changelog
- https://github.com/semantic-release/git

**Comment by MikeMcC399** [comment]
- PR #752 is submitted to resolve this issue

**Comment by mschile** [comment]
@MikeMcC399, I think we should just remove the `extra_plugins` from the workflow and use the release notes on the GitHub release instead of adding a changelog.

**Comment by MikeMcC399** [comment]
@mschile 

>  I think we should just remove the extra_plugins from the workflow and use the release notes on the GitHub release instead of adding a changelog.

That's OK with me.

I'll close the current PR and submit a new one to clean things up.
