### ISSUE TITLE
Wait-on does not wait for Port on Windows Machine

### ISSUE THREAD

**Issue by nitzanashi** [cypress-io/github-action#753]
- This behavior is only when using a windows machine on the CI, and **can not reproduce on Ubuntu or MacOS.**
- We use Webpack to build our application and Cypress Action does not wait on the port which we set, instead the moment we start the build process Cypress is initializing and Start running tests, (which of course fail because the App is not ready)

```
  Running:  login.functional.test.js                                                       (1 of 27)
  Estimated: 20 seconds
(node:1860) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1860) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
(node:1860) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1860) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.

  Login
<i> [webpack-dev-middleware] wait until bundle finished: /login
    1) "before all" hook for "contains form - C78349"
  0 passing (31s)
  1 failing
  1) Login
       Page
         "before all" hook for "contains form - C78349":
     CypressError: `cy.visit()` failed trying to load:
https://localhost:3001/login
We attempted to make an http request to this URL but the request failed without a response.
We received this error at the network level:
  > Error: ESOCKETTIMEDOUT
Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer
Because this error occurred during a `before all` hook we are skipping the remaining tests in the current suite: `Login`
```

**Comment by MikeMcC399** [comment]
@nitzanashi 

Have you tried the `start-windows` parameter when running on Windows?

See [README: Start server](https://github.com/cypress-io/github-action#start-server).

**Comment by MikeMcC399** [comment]
@nitzanashi 

There is an alternative way of using wait-on:

wait-on: 'npx wait-on --timeout 60000 http://localhost:3001'

See also [README: Wait-on](https://github.com/cypress-io/github-action#wait-on).

**Comment by nitzanashi** [comment]
> @nitzanashi
> 
> Have you tried the `start-windows` parameter when running on Windows?
> 
> See [README: Start server](https://github.com/cypress-io/github-action#start-server).

@MikeMcC399 Indeed that was the issue, I Don't know how I missed that! thanks a lot for the very fast response much appreciate it.
