### ISSUE TITLE
Issue with PNPM v7

### ISSUE THREAD

**Issue by naorpeled** [cypress-io/github-action#761]
Hey,
our CI is failing after right after PNPM install,
in the Cypress verify step with the following message: 
```bash
Command failed: /home/runner/work/.../node_modules/.bin/cypress verify
```

Based on [the code](https://github.com/cypress-io/github-action/blob/30008f1458a5a2c97054bfe118fe33d75976c482/index.js#L295) in this repo, it seems that only `npx` is run with `cypress verify`, no matter which package manager we're using.

My guess, is that `pnpm exec` instead of `npx` would make it work properly. I've been migrating our projects from PNPM 6 to 7 in the past few days and had a similar issue with other libs and that seemed to do the trick.

Has anybody else encountered this issue?

**How to reproduce?**
bootstrap a Cypress project with PNPM 7, make sure to not skip the binaries download and that should do the trick.

P.S: sorry for not creating a reproduction repo myself, might have more time for it tomorrow.

**Comment by MikeMcC399** [comment]
@naorpeled 

A reproducible example would be really helpful as I can't see any failures in the examples.

The standard GitHub runners all have Node.js installed by default. Node.js includes npm, and npm includes npx. But maybe you have a different setup?

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
