### ISSUE TITLE
Error: Resource not accessible by integration when running with parallel: true

### ISSUE THREAD

**Issue by wagnerpereira** [cypress-io/github-action#763]
Hey buddies,

I'm stucked trying to get parallel tests to run with: parallel: true.

Without the parallel: true in the action, tests run in parallel( strategy matrix )with success and Cypress Dashboard records like two duplicate tests.

With parallel: true in the action, tests fail with this message error: "Resource not accessible by integration"

**Error:**
![Screen Shot 2023-01-31 at 12 00 57](https://user-images.githubusercontent.com/2737595/215798869-26c31e80-e723-4b19-903a-116986b38d60.png)

**Configuration:**
![Screen Shot 2023-01-31 at 12 03 46](https://user-images.githubusercontent.com/2737595/215798975-82aecc2f-e678-4c41-9a97-8d62d44b43a2.png)

I would like to continue to use this valuable action, thanks for the help.

**Comment by MikeMcC399** [comment]
@wagnerpereira 

"Error: Resource not accessible" is not an error message from [cypress-io/github-action](https://github.com/cypress-io/github-action).

I googled and found that it is most likely to come from the permissions of `GITHUB_TOKEN`.

You might get a better answer from the Cypress community on [Discord](https://discord.gg/cMjUZg7). Good luck!

**Comment by wagnerpereira** [comment]
I'll try to debug it a little more but tried Knapsack github actions integration to split tests and it worked like a charm.

https://github.com/KnapsackPro/knapsack-pro-cypress

**Comment by MikeMcC399** [comment]
@wagnerpereira 

Great that you found a solution! Which version of Cypress are you using? I had a quick look at KnapsackPro and it looked like they support only Cypress 10.

**Comment by wagnerpereira** [comment]
It is working with Cypress 12 @MikeMcC399 

![image](https://user-images.githubusercontent.com/2737595/215878041-d2b275da-da15-465d-bc4d-444531c45d8d.png)

I will wait for a fix in the Cypress official github action / documentation on how to configure parallel tests in our projects.

**Comment by nagash77** [comment]
@wagnerpereira I am glad you are unstuck.  It sounds like this is no longer a problem when using the latest Cypress so I am going to close this issue as resolved.  Feel free to comment here if you are still encountering this problem and we can reopen.

**Comment by macgena** [comment]
I met the same problem, and found a reason. When `parallel: true` is enabled, cypress action tries to build a `ci-build-id`, and make [API calls to the `actions` endpoints](https://github.com/cypress-io/github-action/blob/master/index.js#L539-L566)

To solve, add the following code to GHA action.
```yml
permissions:
  actions: read
```

**Comment by macgena** [comment]
@MikeMcC399 
In case `permissions:` key is not specified is defaults to [this configuration](https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) which includes `actions: write` already.

We have `permissions:` specified for our action as we need `id-token: write` in it, and it's not included by default. When `permissions` are specified you need to add all of them explicitly, that's why I needed to add it.

I think explicit permissions required by Cypress are:
```yml
permissions:
  contents: read
  actions: read
```
In case permissions are not specified at all everything will work fine as well.

**Comment by MikeMcC399** [comment]
@macgena 

Thanks very much! This should probably be added to the documentation for those users who need permissions defined like you.

I'm going to close this issue now and I will follow up with some documentation enhancements.
