### ISSUE TITLE
README Installation minimum Node version

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/github-action#804]
The compatibility of [cypress-io/github-action](https://github.com/cypress-io/github-action) (GHA) to versions of [Node.js](https://nodejs.org/) is currently misleadingly described in [README: Notes > Installation](https://github.com/cypress-io/github-action/blob/master/README.md#installation).

## Current situation

The [README: Notes > Installation](https://github.com/cypress-io/github-action/blob/master/README.md#installation) contains the paragraph:

"This action uses several production dependencies. The minimum Node version required to run this action depends on the minimum Node required by the dependencies."

This statement is at best misleading, at worst inaccurate, and it delegates the responsibility of determining any compatibility answer to the reader.

## Expectation

The documentation should be clear about the compatibility to versions of [Node.js](https://nodejs.org/). Any compatibility changes, which would be caused by GitHub or dependency changes, should be documented in [README: Notes > Installation](https://github.com/cypress-io/github-action/blob/master/README.md#installation). According to the [Semantic Versioning](https://semver.org/) specification any such change in compatibility should result in the release of a new major version of GHA, since this would be a breaking change to GHA.

## Node.js environment

[cypress-io/github-action](https://github.com/cypress-io/github-action) (GHA) v5 runs under node16 according to

https://github.com/cypress-io/github-action/blob/7658659b333a30b2fe39c479e6e5429b637afc07/action.yml#L91

Invoked commands such as `npm ci` run under the Node.js version of the runner which calls GHA. This could be the default Node.js version of the runner (see Language and Runtime section of individual [actions/runner-images](https://github.com/actions/runner-images) for GitHub hosted runners) or a Node.js which has been selected through [actions/setup-node](https://github.com/actions/setup-node) for instance. (The default Node.js version for GitHub hosted runners changed to Node.js 18 on Feb 18, 2023.)

(Refer to log files from https://github.com/cypress-io/github-action/actions/workflows/example-node-versions.yml?query=branch%3Amaster for examples of explicitly selected Node.js versions.)

## GitHub restrictions

GitHub makes certain Node.js versions available for [`runs.using` for JavaScript actions](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsusing-for-javascript-actions). These are currently the [deprecated `node12`](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) version and the `node16` version in Maintenance status.

## Production Dependencies

[package.json](https://github.com/cypress-io/github-action/blob/master/package.json) defines GHA's production dependencies as:

| Dependency                                                                     | Version | Type           | Minimum Node.js         |
| ------------------------------------------------------------------------------ | ------- | -------------- | ----------------------- |
| [@actions/cache](https://github.com/actions/cache)                             | 3.1.2   | JavaScript     | node16                  |
| [@actions/core](https://github.com/actions/toolkit/tree/main/packages/core)    | 1.10.0  | npm            | undefined               |
| [@actions/exec](https://github.com/actions/toolkit/tree/main/packages/exec)    | 1.1.1   | npm            | undefined               |
| [@actions/io](https://github.com/actions/toolkit/tree/main/packages/io)        | 1.1.2   | npm            | undefined               |
| [@octokit/core](https://github.com/octokit/core.js)                            | 4.2.0   | npm            | >= 14                   |
| [argument-vector](https://github.com/cmilhench/argument-vector)                | 1.0.2   | npm (archived) | undefined               |
| [debug](https://github.com/debug-js/debug)                                     | 4.3.4   | npm            | >= 6                    |
| [execa](https://github.com/sindresorhus/execa)                                 | 6.1.0   | npm            | >= 12 (v7 >= 14)        |
| [find-yarn-workspace-root](https://github.com/square/find-yarn-workspace-root) | 2.0.0   | npm            | undefined               |
| [got](https://github.com/sindresorhus/got)                                     | 11.8.6  | npm            | >= 10.19 (v12 >= 14.16) |
| [hasha](https://github.com/sindresorhus/hasha)                                 | 5.2.2   | npm            | >= 8                    |
| [quote](https://www.npmjs.com/package/quote)                                   | 0.4.0   | npm            | undefined               |

According to this, the minimum Node.js version determined by the highest minimum of any of the above npm packages would be Node.js 14 due to [@octokit/core](https://github.com/octokit/core.js) which specifies `engine` >= 14 in its package.json.

## Suggested change

Change [README: Notes > Installation](https://github.com/cypress-io/github-action/blob/master/README.md#installation) from the current:

"This action uses several production dependencies. The minimum Node version required to run this action depends on the minimum Node required by the dependencies."

to

"The app under test runs on the Node.js version provided by the runner where the actions's `use: cypress-io/github-runner@v5` command is placed. For [GitHub-hosted runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners) refer to the [actions/runner-images](https://github.com/actions/runner-images) documentation to find the default Node.js version. An alternative Node.js version can be set up conveniently with [actions/setup-node](https://github.com/actions/setup-node). The [example-node-versions.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-node-versions.yml) workflow demonstrates the action running on supported versions of Node.js.

Refer to the Cypress documentation [Installing Cypress: Node.js](https://on.cypress.io/guides/getting-started/installing-cypress#Nodejs) for the supported versions of Node.js and to the [Cypress Changelog](https://docs.cypress.io/guides/references/changelog) for information on the releases of Cypress. Like Cypress itself, this action also generally aligns with [Node's release schedule](https://github.com/nodejs/Release).

(Note that the core of this action (v5) runs Cypress under the fixed [Node.js](https://nodejs.org/) version 16 according to [`runs.using` for JavaScript actions](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsusing-for-javascript-actions) provided by GitHub. This is the version that you see reported by Cypress in the log summary header in the line `Node Version:` for Cypress 9 and later.)"

Alternatively, don't go into details, but instead use modified text from the [Cypress website](https://on.cypress.io/guides/getting-started/installing-cypress#Nodejs) and list the explicit versions i.e.:

"This action supports:

- **Node.js** 14.x
- **Node.js** 16.x
- **Node.js** 18.x and above

and is generally aligned with [Node's release schedule](https://github.com/nodejs/Release)."

---

## Cypress Documentation Reference

The documentation [Installing Cypress: Node.js](https://on.cypress.io/guides/getting-started/installing-cypress#Nodejs) being referred to says:

### Node.js

If you're using `npm` to install Cypress, we support:

- **Node.js** 14.x
- **Node.js** 16.x
- **Node.js** 18.x and above

Cypress generally aligns with
[Node's release schedule](https://github.com/nodejs/Release).

**Comment by Sija** [comment]
See https://github.com/actions/runner-images/issues/7002 for reference.

**Comment by MikeMcC399** [comment]
@Sija 

> See [actions/runner-images#7002](https://github.com/actions/runner-images/issues/7002) for reference.

Thanks. The GitHub [actions/runner-images](https://github.com/actions/runner-images) which are not deprecated have all been updated to use Node.js 18.14.1 as default.
