### ISSUE TITLE
I also do unit tests on my frontend...

### ISSUE THREAD

**Issue by mg98** [cypress-io/github-action#81]
This action buillds and caches the _node_modules_... which is awesome! But beside from Cypress E2E Tests I also do traditional unit testing... like vue unit testing. So I have other steps/ jobs that rely on the _node_modules_ directory as well.

I understand that this action is supposed to simplify it at maximum for people willing to setup a ci for cypress, but shouldn't we separate it from the preparation of _node_modules_ or make it configurable?
Because I kind of want to do the steps by myself. Otherwise I guess I would just have to make sure I run the cypress action before I do my vue unit testing, but it would not feel right, you understand?

**Comment by bahmutov** [comment]
I suggest creating separate workflows - one for E2E tests that use Cypress, another workflow for other types of tests - and there you can use `@bahmutov/npm-install` to simplify NPM dependency caching. Also you can use env variable to skip Cypress binary installation in that workflow, see example repo https://github.com/bahmutov/cypress-gh-action-split-install
