### ISSUE TITLE
Flaky example-custom-ci-build-id has problems recording into group

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/github-action#819]
The example workflow [example-custom-ci-build-id.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-custom-ci-build-id.yml) fails occasionally.

## Problem description

The [logs](https://github.com/cypress-io/github-action/actions/workflows/example-custom-ci-build-id.yml) from the example workflow [example-custom-ci-build-id.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-custom-ci-build-id.yml) show that it fails occasionally.

Using a search filter [example-custom-ci-build-id.yml - failures](https://github.com/cypress-io/github-action/actions/workflows/example-custom-ci-build-id.yml?query=is%3Afailure) shows that the test fails in:

- all-tests (1)
- all-tests (2)
- all-tests (3)

The error message is:

```text
The run you are attempting to access is already complete and will not accept new groups.

The existing run is: https://cloud.cypress.io/projects/3tb7jn/runs

When a run finishes all of its groups, it waits for a configurable set of time before finally completing. You must add more groups during that time period.

The --tag flag you passed was:
The --group flag you passed was: 2 - all tests
The --parallel flag you passed was: true
The --ciBuildId flag you passed was: sha-d938a73de93081c7aa82cd4528c24e3c5aed2495-time-1671487656

https://on.cypress.io/already-complete
Error: The process '/usr/local/bin/npx' failed with exit code 1
```

## Steps to reproduce

Trigger the workflow and view the [action logs](https://github.com/cypress-io/github-action/actions/workflows/example-custom-ci-build-id.yml).

The workflow [example-custom-ci-build-id.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-custom-ci-build-id.yml) is triggered by:

- push to `master`
- pull request

## Analysis

The workflow starts three identical tests in parallel using [examples/recording](https://github.com/cypress-io/github-action/tree/master/examples/recording).

Run [3735563076](https://github.com/cypress-io/github-action/actions/runs/3735563076) is an example of the workflow failing.

The Cypress Guide [Parallelization: Run completion delay](https://docs.cypress.io/guides/guides/parallelization#Run-completion-delay) contains information about the parameter [Run completion delay](https://docs.cypress.io/guides/cloud/projects#Run-completion-delay) which is set to 60 seconds by default.

| Test          | Time of error | Start of run |
| ------------- | ------------- | ------------ |
| all-tests (1) | 22:11:16      | 22:10:41     |
| all-tests (2) | 22:11:01      | 22:10:40     |
| all-tests (3) | 22:11:36      | 22:10:54     |

The time skew in the tests shows a maximum of 36 seconds which is less that the default timeout [Run completion delay](https://docs.cypress.io/guides/cloud/projects#Run-completion-delay). Cypress Cloud does not display `Project settings` for users with read-only access like myself, so I cannot see the value of the `Run completion delay` parameter for Cypress Cloud project [3tb7jn](https://cloud.cypress.io/projects/3tb7jn).

## Suggested fix

- Review the [Run completion delay](https://docs.cypress.io/guides/cloud/projects#Run-completion-delay) parameter for Cypress Cloud project [3tb7jn](https://cloud.cypress.io/projects/3tb7jn) and consider increasing it. *This is a Cypress Cloud project parameter for https://cloud.cypress.io/projects/3tb7jn. It cannot be set in the repo https://github.com/cypress-io/github-action itself.*

**Comment by MikeMcC399** [comment]
The problem also occurs when renovate pushes multiple branches at the same time which triggers concurrent runs of [example-custom-ci-build-id.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-custom-ci-build-id.yml).

That would be a general issue that probably shouldn't be worked around here in the action.

**Comment by MikeMcC399** [comment]
Possibly [example-custom-ci-build-id.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-custom-ci-build-id.yml) should be restricted so it does not trigger on `push`

```yml
on:
  push:
    branches:
      - 'master'
```

and only uses `pull_request`, which would avoid the Renovate issue.

Another workaround might be to use Renovate's [branchConcurrentLimit](https://docs.renovatebot.com/configuration-options/#branchconcurrentlimit)

"Limit to a maximum of x concurrent branches. 0 means no limit, null (default) inherits value from prConcurrentLimit."

and set this to 1. At the moment the limit is effectively 8.

https://github.com/cypress-io/github-action/blob/88c8045faad8d2f74266a35cc71df2d9e142e83d/renovate.json#L14

**Comment by MikeMcC399** [comment]
This issue has not been occurring often. After a 2 week pause it happened again today.

See https://github.com/cypress-io/github-action/actions/runs/4555148337 (Wed, 29 Mar 2023).

Previous failure was https://github.com/cypress-io/github-action/actions/runs/4429688835 (Wed, 15 Mar 2023).

In this case Renovate was not active at the same time.

**Comment by emilyrohrbough** [comment]
Yeah that is interesting. I kicked off a new workflow and the total duration was `[2m 1s](https://github.com/cypress-io/github-action/actions/runs/4555148337/usage)`. The jobs you have linked have a total duration of [1h 36m 5s](https://github.com/cypress-io/github-action/actions/runs/4555148337/usage) and [5m 33s](https://github.com/cypress-io/github-action/actions/runs/4429688835/usage) so something is throttling/queuing these jobs and the short `Run completion delay` (it is indeed set to 60 seconds) is auto-closing the run before these jobs have a change of starting.

**Comment by emilyrohrbough** [comment]
I would guess the multiple example workflows are fighting for a spot in the queue which is why this example fails so often.

Reading the intent of this example here: https://github.com/cypress-io/github-action#robust-custom-build-id, it does really seem super necessary to demonstrate running a parallel jobs in the workflow. What do you think? Is it worth having both the `smoke-tests` and `all-tests` examples to provide an example of generating and using a Custom Build ID?

**Comment by MikeMcC399** [comment]
@emilyrohrbough 

>  the short Run completion delay (it is indeed set to 60 seconds) is auto-closing the run before these jobs have a change of starting.

![image](https://user-images.githubusercontent.com/66998419/229043695-7d076ade-cc3f-4dd1-b10c-ab07d3efe003.png)

I suggest first taking the pragmatic approach and increasing the completion delay, perhaps to 3 minutes (180 seconds)?

![image](https://user-images.githubusercontent.com/66998419/229044410-f91bc7b3-a6c1-4f2e-ab0e-f4eb5e9098e2.png)

Also it would be a good idea to add timeouts to the jobs so that they don't hang around for hours if there is a failure.

**Comment by MikeMcC399** [comment]
https://github.com/cypress-io/github-action/commit/4056af471d49ea709ddce7ec33fcb59a014041e7 has modified Renovate parameters

https://github.com/cypress-io/github-action/blob/2ff56a151a40fecc036a2d7bd33d23415fb2051a/renovate.json#L14-L15

This should reduce the risk of renovate clashes.

**Comment by MikeMcC399** [comment]
A [search for workflow failures](https://github.com/cypress-io/github-action/actions/workflows/example-custom-ci-build-id.yml?query=is%3Afailure) shows that [example-custom-ci-build-id.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-custom-ci-build-id.yml) last failed 2 months ago due to the issue "The run you are attempting to access is already complete and will not accept new groups.".

Possibly the changes to the renovate config have helped.

Closing due to the issue no longer being reproducible. I will re-open if it looks like the issue needs to be re-examined.
