### ISSUE TITLE
Parallel recording with non-Electron browser needs Docker for reliability

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/github-action#865]
- According to the discussion in https://github.com/cypress-io/github-action/issues/602 a parallel recording workflow using a browser other than the built-in Electron browser may fail with the Cypress error [CLOUD_PARALLEL_GROUP_PARAMS_MISMATCH](https://github.com/cypress-io/cypress/blob/f5bcc044a2ce315778aa8244acaf4ac8db2adf96/packages/errors/src/errors.ts#L280) (see example text below). This can happen if GitHub is in the process of rolling out a change to a [GitHub runner image](https://github.com/actions/runner-images) which includes a major version change of one of the pre-installed browsers. (The `ubuntu` and `windows` runners each include Google Chrome, Mozilla Firefox and Microsoft Edge pre-installed. The `macos` runners additionally include Apple Safari.)

- This is not tested by [.github/workflows/example-recording.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-recording.yml) since this example uses the default Electron browser and it does not use a matrix of containers.

- The [README: Record test results on Cypress Cloud](https://github.com/cypress-io/github-action/blob/master/README.md#record-test-results-on-cypress-cloud) does not use Docker containers, although the GitHub documentation section [GitHub Actions: Parallelization](https://docs.cypress.io/guides/continuous-integration/github-actions#Parallelization) **does** use a Docker container.

## Suggestions

- Add a tip and description of this issue to the list on [README: Record test results on Cypress Cloud](https://github.com/cypress-io/github-action/blob/master/README.md#record-test-results-on-cypress-cloud) recommending the use of a Docker container and explaining when and why it is needed

- Modify the parallel recording examples to use a Docker container, use a matrix strategy and demonstrate usage with Google Chrome instead of Electron:
    - [README: Record test results on Cypress Cloud](https://github.com/cypress-io/github-action/blob/master/README.md#record-test-results-on-cypress-cloud) 
    - [.github/workflows/example-recording.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-recording.yml)

## Example error message

```text
You passed the --parallel flag, but we do not parallelize tests across different environments.

This machine is sending different environment parameters than the first machine that started this parallel run.

The existing run is: https://cloud.cypress.io/projects/xxxxxx/runs

In order to run in parallel mode each machine must send identical environment parameters such as:

 - specs
 - osName
 - osVersion
 - browserName
 - browserVersion (major)

This machine sent the following parameters:

{
  "osName": "linux",
  "osVersion": "Ubuntu - ",
  "browserName": "Chrome",
  "browserVersion": "111.0.5563.146.... (Expected: 112)",
  "specs": [
    ...
  ]
}
```

**Comment by MikeMcC399** [comment]
- Related to core-product issue https://github.com/cypress-io/cypress/issues/25040

**Comment by tianhuil** [comment]
@MikeMcC399: just to comment: we ran today (4/13) two CI jobs within an hour of each other that had these two images:
- https://github.com/actions/runner-images/blob/ubuntu22/20230402.1/images/linux/Ubuntu2204-Readme.md
- https://github.com/actions/runner-images/blob/ubuntu22/20230409.1/images/linux/Ubuntu2204-Readme.md

Note that the first image is 11 days old, and was used even though the 2nd image has been available.  This problem has been around for the last 4 days (the age of the 2nd image)!  These Github rollouts take a lot of time.

**Comment by MikeMcC399** [comment]
@tianhuil 

Thank you very much for confirming what other users are also seeing! Which browser are you testing against?

According to https://github.com/actions/runner-images the `ubuntu-22.04` rollout is now at `99.26%`. See https://github.com/actions/runner-images

![image](https://user-images.githubusercontent.com/66998419/231815205-d08d6460-7cea-485f-9319-c0de4b018cb7.png)

so I imagine that the problem will soon stop being visible. It can be expected to happen again the next time that a major browser version is rolled out.

**Comment by MikeMcC399** [comment]
I have submitted product feedback to GitHub on https://github.com/orgs/community/discussions/52956 "Use same runner image in job matrix containers" so I would like to see if there is any response from GitHub about this issue before making any major changes in the repository here.

**Comment by MikeMcC399** [comment]
This issue should be followed in

- https://github.com/cypress-io/cypress/issues/25040

for the core Cypress product. There is nothing which can be changed in [cypress-io/github-action](https://github.com/cypress-io/github-action) to resolve the issue, apart from providing clearer documentation.

The recommendations for using a Docker container have been added to the [README: parallel](https://github.com/cypress-io/github-action/blob/master/README.md#parallel) example section through PR #870. This clarifies the documentation aspect of the issue.
