### ISSUE TITLE
Missing summary on GitHub Actions Workflow

### ISSUE THREAD

**Issue by cmotsn** [cypress-io/github-action#882]
Hi!

I did not manage to obtain a Cypress summary (ass introduced by #566) shown in the GitHub workflow Summary page, despite having the 
```
      - uses: cypress-io/github-action@v5.5.1
        with:
          // ...
          publish-summary: true
```
input parameter.
The tests are run, I can see a text summary in the Console Output:
```
      Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  tests-non-regression/dummyTest.cy.t      00:10        3        3        -        -        - │
  │    s                                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  tests-sanity/dummyTest.cy.ts             00:10        3        3        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        00:20        6        6        -        -        -  
```

But nothing appears on the Summary apart from the title I defined myself (note: it also doesn't appear without the custom title):
![image](https://user-images.githubusercontent.com/105796626/234286003-b86c10c4-7ebc-4100-84c9-2a2965c5a9e6.png)

Are there other requirements to have the summary displayed (specific reporters, ...) ?

**Comment by MikeMcC399** [comment]
@cmotsn 

The summary should always have the heading "Cypress results" yet your summary says "Manuel summary text". Can you explain where this text might come from?

https://github.com/cypress-io/github-action/blob/a4a03049fbdb67f764a165bc7622df1c1b21b252/index.js#L828

**Comment by cmotsn** [comment]
> @cmotsn
> 
> The summary should always have the heading "Cypress results" yet your summary says "Manuel summary text". Can you explain where this text might come from?
> 
> https://github.com/cypress-io/github-action/blob/a4a03049fbdb67f764a165bc7622df1c1b21b252/index.js#L828

Yes it's a text that I added myself to check whether Summary worked at all. You can ignore this text, if I remove this manual-added step there is NO summary at all writtent :)

**Comment by MikeMcC399** [comment]
There is a similar workflow [.github/workflows/example-chrome.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-chrome.yml) which produces artifacts and summaries.

For comparison see https://github.com/cypress-io/github-action/actions/runs/4797074059

Could you post the beginning of the call to github-action in the logs, like the following?

![image](https://user-images.githubusercontent.com/66998419/234315727-7cf3aeaa-8b70-4863-af3d-dd79ae9d98d5.png)

**Comment by cmotsn** [comment]
> Could you post the beginning of the call to github-action in the logs, like the following?

```
Run cypress-io/github-action@v5
  with:
    config-file: cypress.config-CI.ts
    command: npm run ci:dev
    publish-summary: true
    record: false
    component: false
```

> How did you add a text? That is not a function of github-action.

I simply added a step:
  - name: DEBUG
        run: echo "# Manuel summary text" >> $GITHUB_STEP_SUMMARY

      - uses: cypress-io/github-action@v5
        with:
        // ...

> What is your complete workflow?

I can't post it at the moment, but I'm trying the [.github/workflows/example-chrome.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-chrome.yml) to see if I can reproduce it.

**Comment by MikeMcC399** [comment]
@cmotsn 

The problem is 
`command: npm run ci:dev`

This by-passes a lot of the functions of github-action unfortunately.

**Comment by MikeMcC399** [comment]
@cmotsn 

I'm happy we found the root cause. 🙂 You did not miss anything in the documentation because it doesn't mention it. I will make a proposal to add a caution message to the README.

**Comment by MikeMcC399** [comment]
- Another community member actually submitted a PR https://github.com/cypress-io/github-action/pull/341 two years ago to produce a warning when `command` was used. This was never taken on board. The PR is out-of-date by now and the list of commands is not quite right anymore. Also it doesn't mention the summary (which didn't exist at the time). The first step and quickest action in any case would be to modify the documentation.

**Comment by MikeMcC399** [comment]
- PR https://github.com/cypress-io/github-action/pull/884 is submitted with a suggestion for documentation addition

**Comment by MikeMcC399** [comment]
@cmotsn 

Would you like to close this issue now that your problem has been resolved?

**Comment by cmotsn** [comment]
Yes, thank you !

**Comment by dorsegal** [comment]
@cmotsn How did you managed to upload the summary? Did you change your package.json? or did you upload it manualy?
