### ISSUE TITLE
openssl error

### ISSUE THREAD

**Issue by emmakopf** [cypress-io/github-action#930]
Currently having SSL issues when running cypress tests inside github actions. 

Some fixes I've tried that I found suggested through various googling: 

- Upgrading Node from 14.18.2 -> 16.20.0
- Setting wait-on from `http://localhost:9000` to `http://127.0.0.1:9000` 
- Upgrading github-actions from `v3` to `v5` 
- Removing `wait-on` entirely (ssl error still occurs when running the tests) 

Logs: 
```
Run cypress-io/github-action@v2
  with:
    browser: chrome
    install: false
    config-file: cypress.config.ts
    command-prefix: yarn
    start: node server
    wait-on: http://localhost:9000
    spec: cypress/e2e/reports/*.spec.js
    record: true
Skipping install because install parameter is false
start server "node server command "node server"
current working directory "/home/runner/work/[redacted]/[redacted]"
waiting on "http://localhost:9000" with timeout of 60 seconds
/opt/hostedtoolcache/node/16.20.0/x64/bin/node server
App listening on port 9000!
(node:2057) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use 'node --trace-warnings ...' to show where the warning was created)
(node:2057) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(node:2046) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
http://localhost:9000 timed out on retry 8 of 3, elapsed 94065ms, limit 90000ms
Error: write EPROTO 140525441234816:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
```

These issues don't happen locally when I run tests following the same steps of: 
`yarn build:ci`
`node server`
`yarn cypress run`

**Comment by emmakopf** [comment]
> @emmakopf
> 
> > These issues don't happen locally when I run tests following the same steps of:
> > `yarn build:ci`
> > `node server`
> > `yarn cypress run`
> 
> Which version of Node.js are you running locally? (Also for completeness, which version of Cypress are you running?)

I am running Node.js 16.20.0 and cypress 12.7.0

**Comment by MikeMcC399** [comment]
@emmakopf 

Thanks for the version information!

I would suggest anyway to update to the latest version i.e. `cypress-io/github-action@v5` as there are planned changes in GitHub which will stop earlier versions working sooner or later. `@v2` as shown in your log runs on GitHub using `node12` which is no longer supported, and possibly this could be causing a compatibility issue with AWS. `@v5` runs on GitHub using `node16`.

If updating to `@v5` does not solve your problem, then if you add the following to your workflow, you will see the steps in more detail:

```
  env:
    DEBUG: '@cypress/github-action'
```

**Comment by nagash77** [comment]
Hi @emmakopf , did Mike's suggestions help you solve your issue?

**Comment by MikeMcC399** [comment]
@emmakopf 

We haven't heard back from you. How are you progressing in resolving your issue? It does not look like it is primarily caused by `github-action` and it is more likely to be an app <=> Node.js version incompatibility I would guess.

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
