### ISSUE TITLE
beforeEach only executes once

### ISSUE THREAD

**Issue by far11ven** [cypress-io/github-action#950]
I'm using Cypress v12.15.0 with cucumber-preprocessor v18.0.1, @badeball

I try to clear my temporary test data state after every spec/feature but it runs only once, either its incompatible with cuucmber-pre-processor or there is a issue within cypress itself

```
//runs once before each feature as of Release-v3.0
beforeEach(function () {
  console.log("Executing beforeEach"); 
  cy.log('Test Execution started on : ' + new moment().format('DD-MM-YYYY HH:mm:ss'));
  cy.clearTempState(); //migrated to apiCommonSteps.js
})
```

![image](https://github.com/cypress-io/github-action/assets/26922130/4411afa4-d1fc-4a5a-b6d9-339d7822f5ad)

**Comment by MikeMcC399** [comment]
@far11ven 

This is not an issue with `github-action`.

You may be able to get some help from the Cypress Community on

[![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord)

**Comment by far11ven** [comment]
@MikeMcC399 I think I created this issue in wrong space
