### ISSUE TITLE
Job summary only includes E2E test results, not CT ones

### ISSUE THREAD

**Issue by yann-combarnous** [cypress-io/github-action#952]
I have a gh action that runs E2E tests then CT tests in the same job but different steps.

When looking at generated job summaries, I can only see the results for E2E tests.

Would it be possible to add the summary for CT tests as well?

**Comment by MikeMcC399** [comment]
@yann-combarnous 

Are you using https://github.com/cypress-io/github-action#custom-test-command which suppresses a summary?

CT tests will normally produce a summary, whether they are run separately or not.

Do you have a reproducible example or can you post your workflow here?

**Comment by yann-combarnous** [comment]
> @yann-combarnous
> 
> Are you using https://github.com/cypress-io/github-action#custom-test-command which suppresses a summary?
> 
> CT tests will normally produce a summary, whether they are run separately or not.
> 
> Do you have a reproducible example or can you post your workflow here?

Yes, that was it, my bad. Thx for the quick response!
