### ISSUE TITLE
Release `github-action` for Node.js `node20`

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/github-action#968]
This is an enhancement request for Cypress `github-action`. 

GitHub has now provided support for `node20` in their JavaScript Actions environment. See https://github.com/actions/runner/discussions/2704.

## What would you like?

A new major version of the Cypress `github-action` should be released using GitHub's support for Node.js `20` in GitHub JavaScript Actions.

## Why is this needed?

Cypress needs to be able to run using Node.js `20` and not be restricted to Node.js `16`.

Node.js `16` reaches [end-of-life](https://github.com/nodejs/release#release-schedule) on Sep 11, 2023.

From within `github-action`, the full functionality of Cypress together with Cypress Cloud integration and test summaries is only available when Cypress is called by `github-action` using the [Cypress Module API](https://docs.cypress.io/guides/guides/module-api). This is the default way that the `github-action` calls Cypress since the release of `github-action@v2`. Cypress is called in the context of GitHub's [`runs.using` for JavaScript Actions](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsusing-for-javascript-actions) currently available only as `node16`.

## Other

This enhancement request has a critical dependency on an update to the [`runs.using` for JavaScript Actions](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsusing-for-javascript-actions) environment being provided by GitHub through their [actions/runner](https://github.com/actions/runner).

See https://github.com/actions/runner/discussions/2704 for announcement on the availability of `node20`  support:

> From here, we plan to skip over node 18 and hop on the node 20 LTS release. We are currently working on a date to rollout node 20 and have work in-flight to accomplish this. We will update this discussion in the coming weeks with our plans once we finalize them.

## Workarounds

- The [Custom test command](https://github.com/cypress-io/github-action#custom-test-command) option `command` of `github-action` can be used to call Cypress from the context of the Node.js version set up in the GitHub runner, for instance using [actions/setup-node](https://github.com/actions/setup-node) setting Node.js to `18` or `20`, however this usage bypasses many other functions of `github-action`. It causes many of the other `github-action` options to be ignored and prevents return of detailed results information from the Cypress run, such as the test summary and `resultsUrl`. Using `command` is therefore not a good long-term option.

- An alternative to using the Cypress JavaScript Action `github-action` is to call Cypress from a GitHub workflow directly using [`run`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun), with the same disadvantage as above.

- A further alternative is to call the [Cypress Module API](https://docs.cypress.io/guides/guides/module-api) from a custom script written in JavaScript and called from a custom GitHub Actions workflow. This can be used in a simple way or the full results can be used and processed as needed.

Edit: Above text edited based on information in https://github.com/actions/runner/discussions/2704 Jul 19, 2023.
Updated again on Aug 15, 2023 based on https://github.com/actions/runner/issues/2619#issuecomment-1679003443.
Further update Aug 17, 2023.

**Comment by MikeMcC399** [comment]
I asked GitHub for their plans some time ago. The latest request is in https://github.com/orgs/community/discussions/58226.

**Comment by MikeMcC399** [comment]
GitHub has announced that [GitHub runner release v2.308.0](https://github.com/actions/runner/releases/tag/v2.308.0) includes support for `node20` and that roll-out has started. This should allow the implementation of this feature request once the rollout has completed.

**Comment by MikeMcC399** [comment]
- This feature request is planned for implementation through PR #995. This repo is now using [GitHub runner release v2.308.0](https://github.com/actions/runner/releases/tag/v2.308.0) which includes `node20` support.

**Comment by AtofStryker** [comment]
@MikeMcC399 looks like it worked!
